### ISSUE TITLE
The "X" button is not symmetrical to the archiving progress field

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#764] opened 2021-01-21 12:09 UTC
<img width="397" alt="Screenshot 2021-01-21 at 13 21 40" src="https://user-images.githubusercontent.com/62497891/105350875-11902180-5bec-11eb-95e5-1b7913502e1d.png">
<img width="618" alt="Screenshot 2021-01-21 at 13 24 07" src="https://user-images.githubusercontent.com/62497891/105350884-13f27b80-5bec-11eb-9ef6-214ba2857b44.png">

**Comment by Oleg-Chashko** [comment] 2021-01-21 20:39
The topic is closed, as the lack of symmetry is normal for MacOS.

**Comment by aonez** [comment] 2021-01-23 20:45
I'll take a look anyway Oleg 😉

**Comment by aonez** [comment] 2021-01-23 20:58
This is also caused by the new UI elements in Big Sur. I'm personally not too fond of this new progress bar, is SO slim. But pretty sure I can better align it for Big Sur.

**Comment by Oleg-Chashko** [comment] 2021-01-23 21:09
Hi @aonez 
I deleted the topic for a reason. Leave it as it is, do not think for it. This deviation will be seen by 1%, and 99% of people will not notice until you tell them. Leave it as it is. :)

**Comment by aonez** [comment] 2021-02-19 08:45
@Oleg-Chashko I've tweaked the task window for a better Big Sur integration in the latest 1.2.11. This should be fixed as well. Reopen if you see otherwise.

Salut!

**Closed by aonez** 2021-02-19 08:45 UTC
Labels: Big Sur, enhancement, gui
