### ISSUE TITLE
[BUG] Context menu not working under Box/iCloud folder

### ISSUE THREAD

**Issue by soliujing** [aonez/Keka#913] opened 2021-09-01 09:12 UTC
**What is the issue?**
Context menu not working under Box folder after it using Apple's File Provider APIs.
It does not work under iCloud folder as well.

**Possible root cause:**
Backend file path for box has been changed from "external drive" to "cloud folder (similar to iCloud files)"

**How does one reproduce the issue?**
After Box mirgrated with new file API, it persists all the time.
https://support.box.com/hc/en-us/articles/4404386710419

**Screenshots**
<img width="1038" alt="Snip_20210901_165804" src="https://user-images.githubusercontent.com/46142545/131644998-e79a8840-a0d9-48f3-b327-41174ffac98c.png">
<img width="920" alt="Snip_20210901_171028" src="https://user-images.githubusercontent.com/46142545/131645047-e9606227-3caa-4614-b930-029350b61add.png">

**Debug information (Logs, OS, Hardware, Version, etc.)**
macOS: 12.0 Beta (21A5506j)
Box: Version 2.23.422
Folder: `~/Library/CloudStorage/Box-Box/2021_xxxx/`
iCloud folder: `~/Library/Mobile Documents/com~apple~CloudDocs/Downloads/`

**Comment by aonez** [comment] 2021-09-06 09:58
Hi @soliujing! Try adding the full Home Folder in the Finder Extension list, like that:

<img width="640" alt="Screen Shot 2021-09-06 at 11 57 12" src="https://user-images.githubusercontent.com/480163/132199049-3040d046-6075-4579-b8cb-6b9297226adb.png">

I should check why this is happening with some folders.

**Comment by soliujing** [comment] 2021-09-07 13:54
nope :) it didn't work even after I have enabled for both "home" folder & exactly "iCloud path"

**Comment by aonez** [comment] 2021-09-11 10:02
@soliujing I'm testing this one, no issue but on Big Sur:

<img width="366" alt="Screen Shot 2021-09-11 at 11 59 26" src="https://user-images.githubusercontent.com/480163/132944129-9c6a6781-0c71-42e5-a463-5dc1f8a1535c.png">

The Box folder seems to be created on the user path `/Users/User/Box`

I'll try later in the Monterey beta. Using Box Drive 2.23.426, had to enable system extensions to use it.

**Comment by aonez** [comment] 2021-09-11 11:23
Now I've reproduced the issue with the Box Drive beta for Monterey. Will need to investigate further.

You can still use the services:

![Screenshot 2021-09-11 at 13 22 26](https://user-images.githubusercontent.com/480163/132946213-5d7d9a33-3040-4894-8d1e-1a51afd4756d.png)

**Comment by soliujing** [comment] 2021-09-12 05:38
Sure, thanks @aonez 
The "service" is what I am using now.

**Comment by aonez** [comment] 2023-10-06 17:16
This will be workaround with the introduction of a toolbar item in the Finder in the upcoming version 1.3.5, expected for the next Tuesday. Hopefully it'll be helpful for you.

https://github.com/aonez/Keka/issues/1327#issuecomment-1751122009


Closing in favor of #1327. Thanks again for your feedback an patience @soliujing 🙌🏼

**Closed by aonez** 2023-10-06 17:16 UTC
Labels: bug, context menu, workaround, some fixed, Monterey
