### ISSUE TITLE
[BUG]There was some error accessing the binary "keka7z"

### ISSUE THREAD

**Issue by LoveJessyChen** [aonez/Keka#1002] opened 2021-12-27 08:42 UTC
### Configuration
- Keka version: 1.2.50
- macOS version: 12.1 (21C52)

### Describe the bug
When create a zip or 7z,it will appear:
There was some error accessing the binary "keka7z"

### To Reproduce
1. Go to 'Right Menu'
2. Click on 'Using "KeKa Compressed"'
3. See error

**Comment by aonez** [comment] 2021-12-27 08:52
@LoveJessyChen you’ve downloaded Keka from the web? If so, try this:
https://github.com/aonez/Keka/wiki/Quarantine-(p7zip-error)

**Comment by LoveJessyChen** [comment] 2021-12-27 09:13
Ok,I will try this method！

**Comment by aonez** [comment] 2021-12-27 10:07
Please let me know if that works for you 😊

**Comment by LoveJessyChen** [comment] 2021-12-27 10:12
Ok, I do it and it works well.

**Comment by aonez** [comment] 2021-12-27 11:12
Happy to hear that @LoveJessyChen :)

Dupe of #208

**Closed by aonez** 2021-12-27 11:12 UTC
Labels: bug, duplicated, sandbox, workaround
