### ISSUE TITLE
Update the keka icns [REQ]

### ISSUE THREAD

**Issue by blanksir** [aonez/Keka#832] opened 2021-04-16 06:38 UTC
Update the keka icns，just like the rounded rectangle style of BigSur. I have designed a icns.

https://media.macosicons.com/parse/files/macOSicons/2562745c16c8310983e5256041dca580_Keka.icns

**Comment by aonez** [comment] 2021-04-16 09:30
This is a dupe of #585. You can post your design there 😉

**Closed by aonez** 2021-04-16 09:30 UTC
Labels: duplicated, enhancement
