### ISSUE TITLE
[BUG] Error code 2 using "7zz" - Fatal error

### ISSUE THREAD

**Issue by Inkoming** [aonez/Keka#1443] opened 2024-05-07 09:34 UTC
### Configuration
- Keka version: 1.3.8-r5320 (WEB) (Sandboxed) (en-GB)
- macOS version: 14.4.1 (Build 23E224) (arm64)

### Describe the bug
Trying to compress little files with ZIP output using password (256 zip).
The password length is base64 148 characters using this format: Word---Word---Word (till 148 characters).

### To Reproduce
1. Go to 'Keka' and set zip output (tick "Use AES 256 encryption) + Slow compression.
2. Tick "Exclude Mac resource forks".
3. Tick "Verify compression integrity".
4. Use long password (148 characters, or even 49 characters...).
5. Drag & drop the folder (7 small items) on Keka.
6. Error.

### Expected behavior
Keka should compress.

### Screenshots
None.

### Additional context
Changing the source folder doesn't change anything.
It looks like the problem is the password length.
Do we have a maximum password length? Please specify if it's the case.

[Keka.log](https://github.com/aonez/Keka/files/15233526/Keka.log)

**Comment by Inkoming** [comment] 2024-05-07 09:48
Tested with 7zip output, same long password, no problems.

**Comment by aonez** [comment] 2024-05-07 10:05
@Inkoming just to be sure, what version of 7zip are you using? You mean 7-Zip on Windows? Or is it `p7zip` on the terminal?

**Comment by Inkoming** [comment] 2024-05-07 10:07
@aonez I'm on macOS, so only using Keka to compress to 7zip (no 7zip specific App).

**Comment by aonez** [comment] 2024-05-07 10:09
> Tested with 7zip output, same long password, no problems.

But this test you mentioned here with no problems, was it on macOS on the Terminal?

Both `7zz` and `p7zip` fail on my end with 101 characters password, only for ZIP format. So probably it is limited to 100 characters.

**Comment by Inkoming** [comment] 2024-05-07 10:16
The test with 7zip output (148 characters password) was through Keka on macOS, no Terminal.

**Comment by aonez** [comment] 2024-05-07 10:18
Ah ok you meant the 7Z format, got it. Seems like there's this 100 characters limit for ZIP + AES.

Can you double check if it fails with lower character password on your end? You mentioned 49 characters but I'm unable to reproduce the issue with less than 101 characters.

**Comment by Inkoming** [comment] 2024-05-07 10:25
Tested right now, 99 characters is working, above, not. My bad.
So it's upon zip's side problem right? Maybe we need a warning on Keka to not exceed 99 characters?

**Comment by aonez** [comment] 2024-05-07 10:29
Indeed. Just checked and WinZIP is limited to 99 characters, even for non AES passwords. So non AES compressed with 100+ characters can't be extracted using WinZIP.

> warning on Keka to not exceed 99 characters

That will be it. Thanks a lot for all the feedback @Inkoming.

**Comment by aonez** [comment] 2024-06-24 13:11
This was released with 1.4.0. Thanks again @Inkoming!

**Closed by aonez** 2024-06-24 13:11 UTC
Labels: bug, zip, fixed, 7zz
