### ISSUE TITLE
[REQ] remember the compression and decompression password

### ISSUE THREAD

**Issue by finalcreator** [aonez/Keka#1048] opened 2022-02-17 01:02 UTC
I always use one password to compress files, so I have to enter them everytime I open keka.
at same time my archives usually used serval usual password , I don't want to type them in my mac.

### Describe the solution you'd like
I want keka remember my password in a easy way.

### Describe alternatives you've considered
dont' type same password  again and again.

### Additional context
the maczip and winrar provider such feature.

**Comment by gingerbeardman** [comment] 2022-02-17 11:32
One workaround is to enter the password, then leave Keka open.

**Comment by aonez** [comment] 2022-02-17 11:34
This is coming in next version. Anyway I'm closing this one as a dupe of #26.

<img width="791" alt="Screenshot 2022-02-17 at 12 33 46" src="https://user-images.githubusercontent.com/480163/154473205-b44aa450-5366-487d-bb1c-4b578ddd4709.png">

**Closed by aonez** 2022-02-17 11:34 UTC
Labels: duplicated, enhancement

**Comment by finalcreator** [comment] 2022-05-22 04:48
Can we have multiple default password?
