### ISSUE TITLE
Keka not recognizing .tar files, adding to .tar.tar.gz instead

### ISSUE THREAD

**Issue by akrabu** [aonez/Keka#742] opened 2020-12-24 00:17 UTC
### Configuration
- Keka version: v1.2.6 (4371)
- macOS version: 10.15.7

### Describe the bug

When dragging a .tar to Keka to be compressed, it tries to tarball the tarball - e.g. ".tar.tar.gz"

### To Reproduce

Drag a .tar to Keka, and release under "compress" instead of "extract."

### Expected behavior

Keka should recognize it's a tarball, and just directly use the appropriate compressor - not tarball the tarball, plus compress.

### Screenshots

![](https://user-images.githubusercontent.com/6868732/103044553-c83dab00-4535-11eb-84f4-548e12258ab2.png)

**Comment by aonez** [comment] 2020-12-24 13:29
@akrabu I'm not able to reproduce this issue... Do you reproduce it with any TAR file and any compression format?

**Comment by akrabu** [comment] 2020-12-24 23:15
@aonez Hmm, I just made a tar file.  Then switched to XZ mode.  Drug it over to "compress" - and it tries to name it .tar.tar.xz.  Did the same thing on the GZ tab, same thing - file.tar.tar.gz. 

If I go ahead and create the file.tar.tar.xz - then rename to file.tar.xz...  it still extracts just a tarball, so it's not a naming issue only.

**Comment by aonez** [comment] 2021-01-04 12:07
Ah ok! You have "Always tarball non-archiving formats" option enabled. Fixing this right away!

**Comment by aonez** [comment] 2021-01-10 12:29
Should be fixed in 1.2.7! Thanks @akrabu!

**Closed by aonez** 2021-01-10 12:29 UTC
Labels: bug, fixed
