### ISSUE TITLE
Unzipped app with Keka is not working, trying with built-in Mac app works

### ISSUE THREAD

**Issue by Very-Nice-App** [aonez/Keka#283] opened 2018-09-07 06:03 UTC
Hello people,
this morning I've just downloaded an app, TinyAlarm, from its developer website.
I use Keka as default compression/decompression app.
The MD5 of ZIP is a72c1c019e450e45e8a30afddfe2df64.
If I try to launch the uncompressed package, I got the default popup from Mac that tells me I got a corrupted package and the option to Cancel or Move to Trash.
![2018-09-07 07 55 49](https://user-images.githubusercontent.com/22099883/45201127-43e79100-b274-11e8-9cb6-37648597a8de.png)
If I use built-in decompression app, everything works without issue.

Someone can tell me what's wrong with my Keka install/Mac?

This is the first time I got this, and Keka works for everything else.
Thanks!

**Comment by aonez** [comment] 2018-09-08 06:59
This one is a duplicate of #215. Not sure how to fix that one since Apple does not accept the use of a sandbox exception that solves that one.

**Closed by aonez** 2018-09-08 06:59 UTC
Labels: duplicated, sandbox
