### ISSUE TITLE
Exclude version control information directories such as .git , .svn

### ISSUE THREAD

**Issue by ganl** [aonez/Keka#367] opened 2019-02-17 07:32 UTC
just like this：
![image](https://user-images.githubusercontent.com/11937688/52909814-39bcca80-32c9-11e9-8ae3-2b943af9c1e7.png)

**Comment by aonez** [comment] 2019-02-18 14:11
A custom list would be better with some pre-made examples for repositories, Xcode projects, and so on. Thanks @ganl!

**Comment by aonez** [comment] 2020-06-03 06:06
This was a dupe of #324, didn't notice at the time.

**Closed** 2020-06-03 08:12 UTC
Labels: core, duplicated, enhancement, prioriy
