### ISSUE TITLE
[BUG] From report alert

### ISSUE THREAD

**Issue by enelrehel** [aonez/Keka#1164] opened 2022-09-18 05:52 UTC
Your comments here

---

Error while getting the tasks list (quitting 0):

*** -[NSArray initWithArray:range:copyItems:]: range {0, 5} extends beyond bounds [0 .. 3]

**Comment by aonez** [comment] 2022-09-27 08:49
Dupe of #1153. Thanks for the feedback @enelrehel

**Closed by aonez** 2022-09-27 08:49 UTC
