### ISSUE TITLE
RAR extraction fail

### ISSUE THREAD

**Issue by zstekovic** [aonez/Keka#378] opened 2019-03-05 19:22 UTC
Hello,
I have problem with extraction of big (1.7GB) RAR file.
File have bunch of small EPS/CDR files in archive.
7Zip does not have this problem.

---
Error code 13 using "unrar"
Unknown error
---

**Comment by aonez** [comment] 2019-03-05 19:42
Is it possible that you share that file with me?

**Comment by aonez** [comment] 2019-03-05 19:48
Probably this is a duplicate of #362. Can you test if this Keka build works with that file:

[Keka-unrar570.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-unrar570.7z)

**Comment by zstekovic** [comment] 2019-03-05 19:52
It’s working perfectly now.

btw sorry about duplicate post I did not see #362.

Regards,
-- 
Zarko Stekovic | Creative Power Plant
—
Phone: (206) 446 7889
Address: 334 Wells Ave South – Suite B, Renton, WA 98057
Web: www.creativepowerplant.com

**Comment by aonez** [comment] 2019-03-05 19:54
Just to be sure, you mean it's working with the `Keka-unrar570` build? Thanks @zstekovic!

**Comment by zstekovic** [comment] 2019-03-05 19:55
Yes, the one you send me… 1.1.13 (3268)
-- 
Zarko Stekovic | Creative Power Plant
—
Phone: (206) 446 7889
Address: 334 Wells Ave South – Suite B, Renton, WA 98057
Web: www.creativepowerplant.com

**Comment by aonez** [comment] 2019-03-09 08:54
@zstekovic was that 1.7GB RAR parted, with multiple volumes? Or was it a single RAR file? Thanks!

**Comment by zstekovic** [comment] 2019-03-10 03:26
Single file.
Not a problem.
-- 
Zarko Stekovic | Creative Power Plant
—
Phone: (206) 446 7889
Address: 334 Wells Ave South – Suite B, Renton, WA 98057
Web: www.creativepowerplant.com

**Comment by aonez** [comment] 2019-03-18 12:26
@zstekovic I'm closing this one in favor of #362. Thanks for all the feedback!

**Closed by aonez** 2019-03-18 12:26 UTC
Labels: bug, duplicated, unrar
