### ISSUE TITLE
[REQ] Parallel/Serial Extraction

### ISSUE THREAD

**Issue by baszero** [aonez/Keka#528] opened 2020-03-24 14:41 UTC
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Depending on the device where extraction happens, it's faster if extraction would be serialized, means, if I select four archives to be extracted, only one at a time would be processed, the others queued.

**Describe alternatives you've considered**
no alternatives

**Comment by aonez** [comment] 2020-03-24 14:48
Thanks @baszero! This is already developed in the latests beta versions, if you want to check 😊

This is a duplicate of #21.

**Closed by aonez** 2020-03-24 14:48 UTC
Labels: duplicated, enhancement

**Comment by baszero** [comment] 2020-03-24 14:57
Why is beta not released yet? I don't want to work with beta versions ;-)

**Comment by aonez** [comment] 2020-03-24 15:30
It will be released when it's ready :)
