### ISSUE TITLE
Extracted .app stays in translocation

### ISSUE THREAD

**Issue by boettges** [aonez/Keka#285] opened 2018-09-10 16:41 UTC
Dear @aonez and other keka devs,

I am using Keka 1.1.3 and I use it as my default file archiver.

Running the application "Micro Snitch", downloaded as a zip-file from https://www.obdev.at/products/microsnitch kept giving me the usually just initial warning that I was about to run a application for the first time, asking me whether I was really sure that I want to open it. But no matter how often I accepted the warning, it kept asking upon every new application start.

It turns out that the "Micro Snitch.app", which was unzipped by Keka, was running in AppTranslocation mode for security reasons, because it seems to me that Keka did remove the developer's signature.

I noticed this, because I completely removed the application from my system, re-downloaded the aforementioned zip-file and unzipped it with Keka. I was greeted with the following message:
<img width="547" alt="keka unzip" src="https://user-images.githubusercontent.com/20265197/45309549-36583280-b524-11e8-97ef-557310050a9d.png">
(Please excuse the German locale. It translates to: "Application created by Keka".)
So I cross checked this by unzipping the file using the macOS built-in archiver:
<img width="638" alt="archivierungsprogramm unzip" src="https://user-images.githubusercontent.com/20265197/45309623-5e479600-b524-11e8-96ae-f884ac47a363.png">
Turns out that the built-in tool keeps the developer signatures unimpaired.

I'm a long time Keka-user and never had problems with this in earlier versions of Keka. I guess something must have been changed.

Thanks a lot in advance for looking into it.
Peter

**Comment by aonez** [comment] 2018-09-11 11:28
By the way I'm a long time user of [Little Snitch](https://www.obdev.at/products/littlesnitch/), do you recommend [Micro Snitch](https://www.obdev.at/products/microsnitch)?

**Comment by boettges** [comment] 2018-09-11 11:36
Thanks for your reply.
This is the confusing part. Translocation mode remained despite moving the .app to /Applications/. Actually the app has never been started from outside of the applications folder.

The same issue was causing iTerm2.app to ask me upon each start whether it should move itself to ~/Applications/. 

Once I used the macOS bundled archiver to unzip those apps both warnings did not appear again and both apps are running now as expected.

Sorry, I didn't see #215, I did browse and search the issues, but mainly for "translocation".
Micro Snitch is handy and the obdev.at team very trustworthy. It is more a added safety precaution 🙂

**Comment by aonez** [comment] 2018-09-11 11:40
@boettges made a quick test and can't reproduce this, either with Keka or the bundled macOS archiver:

> kept giving me the usually just initial warning that I was about to run a application for the first time, asking me whether I was really sure that I want to open it. But no matter how often I accepted the warning, it kept asking upon every new application start

Translocation is affecting both equally. Until you move the application to another folder (Applications or Desktop) it will launch in a temporary path. Nothing to do here, as it is a macOS security feature.

**Comment by aonez** [comment] 2018-09-11 11:42
> Translocation mode remained despite moving the .app to /Applications/. Actually the app has never been started from outside of the applications folder.
> 
> The same issue was causing iTerm2.app to ask me upon each start whether it should move itself to ~/Applications/.

Can you reproduce those again?

**Comment by boettges** [comment] 2018-09-11 11:51
Yes, if I analyze the processes of the Micro Snitch app using activitiy monitor it clearly shows that the keka-unzipped one is running in translocation, despite being executed from within /Applications/.

Keka unzipped "Micro Snitch.app":
> Process:         Micro Snitch [476]
> Path:            /private/var/folders/sf/5w49k6_915541f1j7wf0_mr40000gn/T/AppTranslocation/8E9793FC-230C-4375-923F-2A777B6B5B35/d/Micro Snitch.app/Contents/MacOS/Micro Snitch

macOS bundled archiver unzipped "Micro Snitch.app":
> Process:         Micro Snitch [902]
> Path:            /Applications/Micro Snitch.app/Contents/MacOS/Micro Snitch

It might require a restart of the app after a reboot of the system to see the warning.

**Comment by aonez** [comment] 2018-09-17 10:08
@boettges Just reproduced it, but not consistently. It affected a couple of applications. The workaround was moving them to the Desktop and back to the Applications folder.

**Comment by aonez** [comment] 2018-09-17 10:26
This is kind of random. Different applications, same quarantine, some open without translocation, some keep the quarantine thus open with translocation.

**Comment by boettges** [comment] 2018-09-18 12:09
@aonez Maybe it is worth waiting another week for macOS 10.14 to be released and observe the behavior again.
With what apps were you able to reproduce this behavior? Maybe I can try those to check whether it occurs independent of the machine?

Thanks a lot 👌

**Comment by aonez** [comment] 2018-09-24 10:09
@boettges I've tried with multiple third party apps (+15). But they where all compressed by me, and applied a quarantine myself for the test.

I'll check later today with the official Mojave release, but not sure it will make any difference. Also the test will be done with a notarized build of Keka, again don't think it will change anything.

**Comment by gingerbeardman** [comment] 2019-10-27 13:27
This is the problem with #208 for me

Workaround:
```
xattr -cr "/Applications/Keka.app"
open "/Applications/Keka.app"
```

**Comment by aonez** [comment] 2019-10-27 16:35
Tried with FSNotes and after moving/copying it from the Downloads folder to the Desktop/Applications folder it no more was in translocation.

If only this key was permitted: `com.apple.security.files.user-selected.executable`

**Comment by gingerbeardman** [comment] 2019-10-27 17:12
In that case the problem is now: why does moving the app on my setup not give the same results as on your system and remove App Translocation?

**Comment by aonez** [comment] 2020-12-18 13:59
This is most probably fixed with the "Inherit quarantine from downloaded files" option in 1.2.0. This option is enabled by default.

Thanks for all the feedback @boettges!

**Closed by aonez** 2020-12-18 13:59 UTC
Labels: blessed, duplicated, sandbox, works for me
