### ISSUE TITLE
Assign a password to the "* .DMG" image.

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#541] opened 2020-04-08 13:58 UTC
<img width="433" alt="Bildschirmfoto 2020-04-08 um 14 22 42" src="https://user-images.githubusercontent.com/62497891/78792443-69d59a00-79b1-11ea-8ffb-9229ccfc2ac9.png">

**I would like, but not necessarily.**
Assign a password to the "* .DMG" image.
Because "Apple Disk Image" is the native and most common format on MacOS. And since the "Keka" program for MacOS, this is one of the main formats.

**Comment by aonez** [comment] 2020-04-24 10:57
This is a dupe of #230. I've already made lots of tests, it seems not possible at the moment.

**Closed by aonez** 2020-04-24 10:57 UTC
Labels: duplicated, enhancement
