### ISSUE TITLE
[BUG] Keka extraction GUI lost its focus

### ISSUE THREAD

**Issue by Saratxe** [aonez/Keka#1535] opened 2024-10-18 12:28 UTC
I saw too late that this error had already been reported here: https://github.com/aonez/Keka/issues/1518

### Configuration
- Keka version: 1.4.4 (5475)
- macOS version: Sequoia 15.0.1 

### Describe the bug
Using Finder with right-click to extract an (encrypted) archive. The Keka extraction GUI opens, but it's not active. So I've to click into it to enter the password. That's annoying.
If Keka is running before I open the (encrypted) archive, the extraction GUI is active. In that case I can enter the password directly.

### To Reproduce
1. Finder -> right-click -> open with Keka (Keka isn't running in the background!)
2. The extraction GUI opens, but it's not active
3. click into it, then I can enter the password

### Expected behavior
The extraction GUI should be active and not lost its focus.

**Comment by aonez** [comment] 2024-10-18 12:51
Dupe of https://github.com/aonez/Keka/issues/1518, as you've seen later 😛

Please check if the updated build fixes the issue for you: https://github.com/aonez/Keka/issues/1518#issuecomment-2416272552

**Closed** 2024-10-18 16:58 UTC
Labels: bug, duplicated
