### ISSUE TITLE
Mixup capitals/non-capitals

### ISSUE THREAD

**Issue by loewal** [aonez/Keka#527] opened 2020-03-22 09:08 UTC
Hi,
I downloaded a zip-file from https://github.com/f4exb/sdrangel/releases/tag/v5.3.1
Trying to compile I noticed an error on a file with a name with mixed capitals and non-capitals.
There it went wrong. i.e.
NameSetApi became Namesetapi...this is just an example.

But not always!!!!

Had to switch back to macos unarchive!!

**Comment by aonez** [comment] 2020-03-22 09:13
Hi @loewal! Thanks for the feedback :)

I'm just trying to reproduce this but I'm not sure where this file `NameSetApi` (or is it a method?) should be.

https://github.com/f4exb/sdrangel/search?q=NameSetApi&unscoped_q=NameSetApi

Searching for it in the repo has no result.

**Comment by loewal** [comment] 2020-03-22 09:17
I am sorry...this is the link of that file
https://github.com/f4exb/sdrangel/releases/tag/v5.3.1
There is a sourcecode file.
Extracting is going 'ok', but when compiling the error occurs.
I'll try to send you a chunk of the compilationprocess.

**Comment by loewal** [comment] 2020-03-22 09:25
The errors....

SWGDeviceSetApi
/Users/loewal/Downloads/sdrangel-5.3.1/swagger/sdrangel/code/qt5/client/SWGDevicesetApi.h:35:7: note: 'SWGDeviceSetApi' declared here
class SWGDeviceSetApi: public QObject {
      ^
/Users/loewal/Downloads/sdrangel-5.3.1/swagger/sdrangel/code/qt5/client/SWGDevicesetApi-1.cpp:22:18: error: missing return type for function 'SWGDevicesetApi'; did you mean the constructor name 'SWGDeviceSetApi'?
SWGDevicesetApi::SWGDevicesetApi() {}
                 ^~~~~~~~~~~~~~~
                 SWGDeviceSetApi
/Users/loewal/Downloads/sdrangel-5.3.1/swagger/sdrangel/code/qt5/client/SWGDevicesetApi-1.cpp:24:1: error: use of undeclared identifier 'SWGDevicesetApi'; did you mean 'SWGDeviceSetApi'?
SWGDevicesetApi::~SWGDevicesetApi() {}
^~~~~~~~~~~~~~~
S

When extracting with macos builtin...all goes fine

**Comment by aonez** [comment] 2020-03-22 10:03
Now I see. @loewal the problem here is that the source code has indeed two versions of the file, it must be in a case sensitive file system and probably @f4exb didn't noticed it.

The macOS bundled extractor just overwrites the lower case `SWGDevicesetApi` into `SWGDeviceSetApi`, because the later is extracted first. This is even worst because the lower case is an outdated file with version 5.1.0 while the upper case is version 5.3.0. Keka notes the difference and deppending on the file system you're extracting to it renames the lower case to `SWGDevicesetApi_1` or respects the two versions.

The older version 5.1.0 has the class declared in lower case `SWGDevicesetApi` and I suppose the rest of the code is linked to this class name, that's why the compiler asks for it. With Keka the newer version file 5.3.0 is used but there the class is defined with upper case `SWGDeviceSetApi`, so the compiler fails.

See here the offending files:

- [SWGDeviceSetApi.h](https://github.com/f4exb/sdrangel/blob/master/swagger/sdrangel/code/qt5/client/SWGDevicesetApi.h) (upper case latest 5.3.0 version)
- [SWGDeviceSetApi.cpp](https://github.com/f4exb/sdrangel/blob/master/swagger/sdrangel/code/qt5/client/SWGDevicesetApi.cpp) (upper case latest 5.3.0 version)
- [SWGDevicesetApi.h](https://github.com/f4exb/sdrangel/blob/master/swagger/sdrangel/code/qt5/client/SWGDevicesetApi.h) (lower case 5.1.0 version)
- [SWGDevicesetApi.cpp](https://github.com/f4exb/sdrangel/blob/master/swagger/sdrangel/code/qt5/client/SWGDevicesetApi.cpp) (lower case 5.1.0 version)

Listing of the ZIP contents (two first/last selected files):

![Screen Shot 2020-03-22 at 10 44 53](https://user-images.githubusercontent.com/480163/77246703-31e8fb80-6c2a-11ea-8b5e-c7f49652c600.png)

**Comment by aonez** [comment] 2020-03-22 10:09
Just reported it: https://github.com/f4exb/sdrangel/issues/490

**Comment by loewal** [comment] 2020-03-22 10:11
Thank you very much.

So ….not use Keka for the time being?

 

Grtz,

 

Loe Walter

Insula 103

6416 BZ  Heerlen

 

☎️0031-6-24476963

 

 

Van: aONe <notifications@github.com>
Beantwoorden - Aan: aonez/Keka <reply@reply.github.com>
Datum: zondag 22 maart 2020 om 11:09
Aan: aonez/Keka <Keka@noreply.github.com>
CC: Loe Walter <lwalter@home.nl>, Mention <mention@noreply.github.com>
Onderwerp: Re: [aonez/Keka] Mixup capitals/non-capitals (#527)

 

Just reported it: f4exb/sdrangel#490

**Comment by aonez** [comment] 2020-03-22 10:14
> So ….not use Keka for the time being?

But the contrary... Not using Keka in this case mean using obsolete code, even if it compiles. This should be fixed in the repository.

macOS extraction is worst in this case. Even if it compiles it is just overwriting a file.

**Comment by loewal** [comment] 2020-03-22 10:16
Ok 👍 😃

 

Loe Walter

Insula 103

6416 BZ  Heerlen

 

☎️0031-6-24476963

 

 

Van: aONe <notifications@github.com>
Beantwoorden - Aan: aonez/Keka <reply@reply.github.com>
Datum: zondag 22 maart 2020 om 11:15
Aan: aonez/Keka <Keka@noreply.github.com>
CC: Loe Walter <lwalter@home.nl>, Mention <mention@noreply.github.com>
Onderwerp: Re: [aonez/Keka] Mixup capitals/non-capitals (#527)

 

So ….not use Keka for the time being?

But the contrary... Not using Keka in this case mean using obsolete code, even if it compiles. This should be fixed in the repository.

macOS extraction is worst in this case. Even if it compiles it is just overwriting a file.

**Closed** 2020-03-22 19:54 UTC
Labels: works for me
