### ISSUE TITLE
Request to improve intelligibility in Error Message windows

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#779] opened 2021-01-28 15:34 UTC
https://user-images.githubusercontent.com/62497891/106160480-29d0e500-6186-11eb-86b2-d730623d8f85.mov

Request to improve intelligibility in all Error Message windows. 
To make it clear to an ordinary user, he did something wrong or this application does not work correctly.
And the error number does not give an ordinary user any information to understand what the problem is, for example: 
<img width="435" alt="Screen Shot 2021-01-28 at 16 26 54" src="https://user-images.githubusercontent.com/62497891/106160392-1160ca80-6186-11eb-8327-e25729e483cb.png">

-------------------------------------------------------------------------------------------------------------------
**I would like to for example:**
<img width="511" alt="Screen Shot 2021-01-28 at 16 03 07" src="https://user-images.githubusercontent.com/62497891/106160828-8c29e580-6186-11eb-8003-f270a7fb2a78.png">

**Comment by aonez** [comment] 2021-01-28 16:47
Thanks Oleg! This is a dupe of #116

**Closed by aonez** 2021-01-28 16:47 UTC
Labels: duplicated, enhancement
