### ISSUE TITLE
During password verification, the application freezes a little

### ISSUE THREAD

**Issue by Oleg-Chashko** [aonez/Keka#749] opened 2021-01-07 14:24 UTC
### Configuration
- Keka version: 1.2.7 (4394)
- macOS version: 11.1 (20C69)

During the creation of the archive when verifying the password, the application freezes a little.

![2021-01-07_15-08-31 (2)](https://user-images.githubusercontent.com/62497891/103903144-ceb65000-50fb-11eb-9cb4-6ca49acfce44.gif)

**Comment by aonez** [comment] 2021-01-07 14:28
I can't reproduce this one. Can you check in the Console.app to see if there's any message there? I can only think there's some issue with the sound that's played when closing the padlock.

**Comment by Oleg-Chashko** [comment] 2021-01-07 14:55
[Console log.txt](https://github.com/aonez/Keka/files/5782250/Console.log.txt)
["keka7z_2021-01-07-150429_MacBook-Pro.crash".zip](https://github.com/aonez/Keka/files/5782252/keka7z_2021-01-07-150429_MacBook-Pro.crash.zip)
Crashes are when you enter a very long and incorrect password to the zip archive.

**Comment by Oleg-Chashko** [comment] 2021-01-07 15:02
_I can only think there's some issue with the sound that's played when closing the padlock._
You were right, this is a sound problem!

**Comment by Oleg-Chashko** [comment] 2021-01-07 16:12
@aonez 
I found the problem with the sound freezes in "Big Sur": When headphones are connected via Bluetooth, the system sounds are a little late, the delay is about 1-1.5 seconds. In this mode, only the "Keka application" freezes. As soon as you turn off the headphones, in "Big Sur" and "Keka application" the sound freezes stop being present. 0_o
_If you can, make the Keck application not wait for a sound from the system. That there were no friezes._

**Comment by aonez** [comment] 2021-01-13 17:09
I'm unable to reproduce the sound issue in Big Sur (or Catalina). I've tried with a UE Boom speaker and some Xiaomi Mi True Wireless Earbuds.

For sound playing the standard SDK methods are used and they play sound asynchronous, so there must be another problem there...

> Crashes are when you enter a very long and incorrect password to the zip archive.

How long was the password?

**Comment by Oleg-Chashko** [comment] 2021-01-13 17:23
@aonez 
_Crashes are when you enter a very long and incorrect password to the zip archive.
How long was the password?_
I can't say for sure, 80-130 characters. Random character set.

P.S.: The sound problem was fixed through the terminal. The topic can be closed. Thank you.

**Closed** 2021-01-14 13:18 UTC
Labels: bug, works for me
