### ISSUE TITLE
files' name isnot correct

### ISSUE THREAD

**Issue by kiongweidong** [aonez/Keka#199] opened 2018-06-06 01:00 UTC
Almost everytime i use keka to archive files, i get the wrong name, but if i use another app to archive files the names are correct
![2018-05-29 19 24 08](https://user-images.githubusercontent.com/22461977/41010075-fd5e43a0-6967-11e8-9a20-919ab923d02b.png)
![2018-05-29 19 24 29](https://user-images.githubusercontent.com/22461977/41010077-ff141ae4-6967-11e8-8f91-692bbbe41eac.png)

**Comment by aonez** [comment] 2018-06-06 07:01
This one is a duplicate of #12. Can you confirm this only happens with Zip files, and only with Zip files created on some Windows machines?

**Comment by aonez** [comment] 2018-06-19 07:32
Closing in favorof #12.

**Closed by aonez** 2018-06-19 07:32 UTC
Labels: duplicated
