### ISSUE TITLE
[REQ] Add support for lrz / lrztar

### ISSUE THREAD

**Issue by zenspider** [aonez/Keka#549] opened 2020-04-23 19:36 UTC
I've been testing lrz against some of my larger archives and even with default settings (eg not `-9` etc) it's beating them out. Also it uses ALL the available CPU so it seems to do it at a very nice clip as well. Would you be open to adding this compression format?

**Comment by aonez** [comment] 2020-04-24 09:03
Thanks @zenspider! It's already in the list #84. Did some tests yesterday with the stable version 0.631 and found no improvements over 7Z, that also uses LZMA. Only using zpaq `-z` got some better results but not consistent and the time spent was crazy. Can you show some of your results?

If I see fit for it would be easy to support it in Keka :)

**Comment by aonez** [comment] 2020-04-26 10:28
Had some time and went ahead with this one. The progress bar is a little useless sometimes due to the steps used in LRZIP.

I'm using LZMA compression but ZPAQ on the slowest setting.

https://d.keka.io/test/Keka-LRZIP

**Comment by zenspider** [comment] 2020-04-27 19:21
Awesome. Thank you... If it's the same algs as 7Z then maybe I should just switch over to that. I'm good either way as long as I get those compression ratios.

**Comment by aonez** [comment] 2020-04-28 16:09
I'm adding it because ZPAQ, that sometimes has better ratio than LZMA! It is very, very slow but might be worth in some cases.

**Comment by akrabu** [comment] 2020-05-02 23:46
> Had some time and went ahead with this one. The progress bar is a little useless sometimes due to the steps used in LRZIP.
> 
> I'm using LZMA compression but ZPAQ on the slowest setting.
> 
> https://d.keka.io/test/Keka-LRZIP

So I tried using this version to extract an XZ archive containing an IMG file to test compression with, but after extraction the file just disappears haha. I tested it twice. It puts original in the trash, and the extracted file disappears. Just a heads up!

**Comment by aonez** [comment] 2020-05-03 09:43
@akrabu can you reproduce this while in a [Keka debug session](https://github.com/aonez/Keka/wiki/Report-an-issue)? Late 1.2.0 builds use a new extraction step, maybe it's failing for you. Also use a fallback folder (Desktop by default), check it's not going there the extraction.

![Screen Shot 2020-05-03 at 11 41 54](https://user-images.githubusercontent.com/480163/80910932-375e5900-8d33-11ea-9a52-0c5324dea316.png)

**Comment by akrabu** [comment] 2020-05-07 16:40
@aonez Actually the file was on my desktop.  And, if I try to extract the Keka-LRZIP.7z itself, with the version from within Keka-LRZIP.7z, it does the same thing.  

I then gave the new Keka full disk access.  Still doesn't work.  :(

**Comment by aonez** [comment] 2020-05-07 17:46
Thanks for the time @akrabu! So seems to be the new extraction step:

```sh
2020-05-07 09:42:00.154 The extraction at /Users/akrabu/Desktop/Keka-LRZIP.kextraction/Operation is empty
```

Is ok to you if I send you a build with more logging for this issue?

**Comment by akrabu** [comment] 2020-05-07 18:12
Absolutely!  :)

**Comment by akrabu** [comment] 2020-06-11 01:32
@aonez Everything seems to get stuck after 5 seconds of extraction...

![Screen Shot 2020-06-10 at 6 30 09 PM](https://user-images.githubusercontent.com/6868732/84335020-b2900780-ab48-11ea-9673-061244faf70e.png)

![Screen Shot 2020-06-10 at 6 32 33 PM](https://user-images.githubusercontent.com/6868732/84335046-c3407d80-ab48-11ea-82b9-8f97c4ed1fcd.png)

**Comment by aonez** [comment] 2020-06-11 08:39
@akrabu can you check on the Console.app (filtered by Keka) if there are any more logs while you do an operation?

**Comment by akrabu** [comment] 2020-07-21 16:55
@aonez Hey, sorry, I missed this message!  But, v1.2.0-beta.1 appears to have fixed the problem.  The latest betas weren't working for me at all and I started to use the main version.  This one finally extracts though!  Though it doesn't always show progress (like no window at all)?  But at least it works haha

**Comment by aonez** [comment] 2020-07-21 20:22
Glad to hear that @akrabu! 👏🏼

> Though it doesn't always show progress (like no window at all)?

By design in 1.2.0 Keka waits 0.5 seconds to show the tasks window. If the operation lasts less than that, you won't see the task window. Is that the case? Or is this happening with longer tasks?

**Comment by akrabu** [comment] 2020-07-21 20:36
Ahhh, I believe that's the case.  Thanks!

**Comment by akrabu** [comment] 2020-07-24 01:41
@aonez Spoke too soon - I'm extracting a 16GB multi-part RAR file and it's definitely working, and I see the pie-chart progress in the Finder, but there's no progress window anywhere.  Just a heads up!

**Comment by aonez** [comment] 2020-07-24 09:40
@akrabu what machine are you using? Any special configuration that I can try to reproduce? Working on an external disk/format?

Maybe you can take a look at the `Console.app` (filtered with Keka) to see if there's any message regarding the tasks window or the stall end...

**Comment by aonez** [comment] 2020-07-24 10:00
@akrabu reproduced the no show tasks window. Going to fix that!

**Comment by akrabu** [comment] 2020-07-25 18:20
@aonez Looks like the extraction bug has popped back up.

<img src="https://i.imgur.com/01E1Rhy.png" />

![Screen Shot 2020-07-25 at 11 14 01 AM](https://user-images.githubusercontent.com/6868732/88463486-f2e0e600-ce67-11ea-89e7-2cb91b3cf8d4.png)

![Screen Shot 2020-07-25 at 11 14 20 AM](https://user-images.githubusercontent.com/6868732/88463494-fe341180-ce67-11ea-8edc-7b163153e1b2.png)

> 2020-07-25 11:10:29.843 Dev mode enabled
> 2020-07-25 11:10:29.844 READER: Dev reader mode enabled


> 2020-07-25 11:10:29.845 NOTIFICATION: Dev notifications mode enabled
> 2020-07-25 11:10:29.845 Running on OS X/macOS version 10.15.6 (Build 19G73)
> 2020-07-25 11:10:29.846 Running sandboxed Keka (WEB) version 1.2.0-beta.1 (3988)
> 2020-07-25 11:10:29.847 Used localization: en
> 2020-07-25 11:10:40.681 DEV: Checking tasks queue
> 2020-07-25 11:10:40.688 DEV: Starting queued task
> 2020-07-25 11:10:40.691 DEV: Path set as unavailable: /Users/akrabu/Downloads/test.kextraction
> 2020-07-25 11:10:40.700 DEV: Format detected: ZIP
> 2020-07-25 11:10:40.701 DEV: Binary used: kekaunar
> 2020-07-25 11:10:40.703 DEV: Arguments: (
>     "-q",
>     "-r",
>     "-K",
>     "-nq",
>     "-o",
>     "/Users/akrabu/Downloads/test.kextraction/Operation",
>     "/Users/akrabu/Downloads/test.zip"
> )
> 2020-07-25 11:10:49.345 DEV: Checking ended task
> 2020-07-25 11:10:49.346 DEV: Skipping quarantine...

Is there any way to toggle showing the extraction window?  I have to queue up a second task to be able to cancel the first, and it makes the log messy haha.  But basically it just sits there at this point.  No errors or anything.  So then I queue up a second extraction, cancel it, plus the first, in order to make it stop.

**Comment by aonez** [comment] 2020-07-26 11:51
I'll push the task window fix in a few

**Comment by aonez** [comment] 2020-07-26 14:09
@akrabu the task window bug is fixed https://github.com/aonez/Keka/releases/tag/v1.2.0-beta.2, can you check there the logs?

**Comment by akrabu** [comment] 2020-07-28 18:52
@aonez I'm testing with an 834MB zip file, and I **do** get the window now!  However, it still stops at the very end.  It isn't frozen, it just doesn't finish.  I still have full-disk access enabled.

![Screen Shot 2020-07-28 at 11 51 13 AM](https://user-images.githubusercontent.com/6868732/88708551-a47e5200-d0c8-11ea-985c-e6957fdc0110.png)

> 2020-07-28 11:50:51.370 Dev mode enabled
> 2020-07-28 11:50:51.372 Running on OS X/macOS version 10.15.6 (Build 19G73)
> 2020-07-28 11:50:51.374 Running sandboxed Keka (WEB) version 1.2.0-beta.2 (4008)
> 2020-07-28 11:50:51.378 Used localization: en
> 2020-07-28 11:50:51.910 DEV: Adding 1 files
> 2020-07-28 11:50:51.911 DEV: Waiting for more input: 0.250000
> 2020-07-28 11:50:51.913 DEV: Requesting access to all bookmarks
> 2020-07-28 11:50:51.915 DEV: Bookmarks updated: 2
> 2020-07-28 11:50:52.287 DEV: Checking tasks queue
> 2020-07-28 11:50:52.299 DEV: Starting queued task
> 2020-07-28 11:50:52.302 DEV: Path set as unavailable: /Users/akrabu/Downloads/test.kextraction
> 2020-07-28 11:50:52.314 DEV: Format detected: ZIP
> 2020-07-28 11:50:52.316 DEV: Binary used: kekaunar
> 2020-07-28 11:50:52.318 DEV: Arguments: (
>     "-q",
>     "-r",
>     "-K",
>     "-nq",
>     "-o",
>     "/Users/akrabu/Downloads/test.kextraction/Operation",
>     "/Users/akrabu/Downloads/test.zip"
> )
> 2020-07-28 11:50:52.736 DEV: Showing delayed tasks
> 2020-07-28 11:51:06.585 DEV: Checking ended task
> 2020-07-28 11:51:06.586 DEV: Skipping quarantine...
> 2020-07-28 11:51:24.283 Dev mode enabled
> 2020-07-28 11:51:24.284 READER: Dev reader mode enabled
> 2020-07-28 11:51:24.285 NOTIFICATION: Dev notifications mode enabled
> 2020-07-28 11:51:24.287 Running on OS X/macOS version 10.15.6 (Build 19G73)
> 2020-07-28 11:51:24.288 Running sandboxed Keka (WEB) version 1.2.0-beta.2 (4008)
> 2020-07-28 11:51:24.289 Used localization: en
> 2020-07-28 11:51:39.089 DEV: Checking ended task
> 2020-07-28 11:51:39.090 DEV: Ignoring queue check, already quitting
> 2020-07-28 11:51:39.091 DEV: Cancelled
> 2020-07-28 11:51:39.093 DEV: (
>     "Format detected: ZIP",
>     "Binary used: kekaunar",
>     "Arguments: (\n    \"-q\",\n    \"-r\",\n    \"-K\",\n    \"-nq\",\n    \"-o\",\n    \"/Users/akrabu/Downloads/test.kextraction/Operation\",\n    \"/Users/akrabu/Downloads/test.zip\"\n)",
>     Cancelled
> )
> 2020-07-28 11:51:39.108 DEV: Path set as available: /Users/akrabu/Downloads/test.kextraction
> 2020-07-28 11:51:39.109 DEV: Operation cancelled
> 2020-07-28 11:51:39.111 DEV: Stopping access to all bookmarks
>

**Comment by aonez** [comment] 2020-07-29 09:10
Finally reproduced the issue! There's a bug that if you have "Inherit quarantine from downloaded files" disabled, the task does never finish (but the extraction does).

Fixing it right away! Thanks a lot @akrabu!

~You can enable that option meanwhile, I'll push this fix in the third beta in a few days.~

Fixed in this build: https://d.keka.io/test/Keka-v1.2.0-dev.r4019

You can simply replace your current beta with this one :)

**Comment by akrabu** [comment] 2020-08-07 16:52
@aonez Yay that fixed it!  Never would have thought of that option as being the culprit haha.  Thanks!

**Comment by aonez** [comment] 2020-08-10 07:34
Nice @akrabu! 😁

**Closed by aonez** 2020-08-10 07:34 UTC
Labels: core, enhancement, fixed
