### ISSUE TITLE
Add or remove files to/from existing archive

### ISSUE THREAD

**Issue by jicho** [aonez/Keka#784] opened 2021-02-09 16:08 UTC
### Is your feature request related to a problem? Please describe
Can't add extra/new files an newly created archive, or remove a single file

### Describe the solution you'd like
It would be nice to be able to add and remove files to/from an existing archive.
Maybe it's me, but I can't figure it out how to do that in Keka, it would be nice to have that option.

This probably involves the need to have "file browser"/manager or something like that.

**Comment by MaxPower85** [comment] 2021-02-16 04:04
Even with archivers that support it, you may get better compression if you just recompress the whole archive. Results may vary depending from what you are compressing, but in some cases it could even be a very significant difference in the file size if the files inside that archive share a lot of the same data.

If each file in an archive is compressed separately, then something like that would be easier to do without recompressing the whole archive every time it is edited, but if the files share a lot of the same data (for example, if you just have different versions of the same app in an archive and they mostly reuse the same code), then the archiver could just compress that data once and reuse it every time it appears for other similar files instead of having duplicated parts of compressed data in the archive.

**Comment by aonez** [comment] 2021-02-17 16:19
Thanks for the feedback @jicho! This is a dupe of #100.

**Closed by aonez** 2021-02-17 16:19 UTC
Labels: duplicated, enhancement
