### ISSUE TITLE
Keka zip not preserving resource forks or something

### ISSUE THREAD

**Issue by pen-helm** [aonez/Keka#917] opened 2021-09-28 03:31 UTC
### Configuration
- Keka version: Version 1.2.17 (4634)
- macOS version:10.14.6

### Describe the bug
Keka does not appear to be perfectly handling old Mac files.

I wanted to unStuff an old app with resource forks and reZip it, so I'd be able to use it in the future.  I unStuffed (with Stuffit Expander, which resulted in a working app.)  Then I zipped with Keka, unzipped with Keka and tested.  It doesn't work.

In the emulator, the version from the zip file doesn't appear as an app.  When I try to launch it, it says it's a document with no app to launch it.

 <img width="445" alt="Screen Shot 2021-09-27 at 11 26 22 PM" src="https://user-images.githubusercontent.com/38336448/135038422-12d743d9-a40f-4d26-aa5c-6d3c51af0f0f.png">

.
<img width="350" alt="Screen Shot 2021-09-27 at 11 21 32 PM" src="https://user-images.githubusercontent.com/38336448/135038513-45a737af-9653-41dd-9e89-dc3ce52c9b84.png">

### Expected behavior
I expected to be able to properly compress and decompress and run the app.

Here's a log from Keka.

[Keka_2021-09-27-232933577.log](https://github.com/aonez/Keka/files/7241854/Keka_2021-09-27-232933577.log)

**Comment by aonez** [comment] 2021-09-29 10:31
Hi @pen-helm! This is a duplicate of https://github.com/aonez/Keka/issues/90. You can alternatively use TAR, GZIP, BZIP ISO or DMG to preserve the forks with Keka. Nice GUI had Mac then, never used that OS.

**Closed** 2021-09-29 10:31 UTC
Labels: bug, duplicated
