### ISSUE TITLE
[BUG] Keka always creates a folder with the archive name when unpacking.

### ISSUE THREAD

**Issue by Drovosek01** [aonez/Keka#922] opened 2021-10-10 16:29 UTC
### Configuration
- Keka version: 1.2.18
- macOS version: 10.14.6

### To Reproduce
1. I went to the program settings and selected the default action - "Always unpack".
2. Then I went to the "Unpack" tab and made sure that there was no check mark "Always unpack to a subfolder".
3. Then I dragged it into the window with keka .zip archive and when unpacking , a folder with the same name as was created in the archive folder .zip archive and all files were unpacked into it.

### Expected behavior
Inside there were no folders in the zip archive, there were only files. I don't want folders to be created during unpacking, I want files from the archive to be unpacked to the same folder where the archive is located without creating additional folders. How do I do this?

### Screenshots
![image](https://user-images.githubusercontent.com/29478700/136704801-0ef6154e-9fc7-467b-86dd-36a1e5cf93aa.png)
![image](https://user-images.githubusercontent.com/29478700/136704808-7f6bb2da-0109-4360-aacb-ded4790e8628.png)
![image](https://user-images.githubusercontent.com/29478700/136704812-138bd443-5455-4d85-8138-a114b5684176.png)

### Additional context
Zip archive for test
[d29e7xmk.zip](https://github.com/aonez/Keka/files/7317813/d29e7xmk.zip)
.

**Comment by aonez** [comment] 2021-10-13 16:16
This is a duplicate of #72. Right now Keka can't extract without that intermediate folder. Any update to this will be posted on #72.

**Closed as completed by aonez** 2021-10-13 16:16 UTC
Labels: bug, duplicated
