### ISSUE TITLE
[BUG] Double Extension Added when Compressing Tar + Other

### ISSUE THREAD

**Issue by LloydThinks** [aonez/Keka#1388] opened 2024-01-24 12:05 UTC
### Configuration
- Keka version:1.3.6 (5281)
- macOS version: 14.3 (23D56)

### Describe the bug
When I compress a file with XZ, LRZIP, or any other that creates a TAR first, the extension is doubled up. E.g. `Acumen.tar.lrz.tar.lrz` or `Acumen.tar.gz.tar.gz`.

### To Reproduce
1. Enable setting "Always tarball non-archiving formats"
2. Disable setting "Use short tarball extensions"
3. Open Keka window
4. Select format that uses TAR (e.g. XZ or GZIP)
5. Drag a folder into the Keka window to trigger the "Compress" action
6. The auto-generated name has double extensions

### Expected behavior
I expect the auto-generated name to not have double extension, but rather the expected extension.

### Screenshots
![Screenshot 2024-01-24 13-04-20](https://github.com/aonez/Keka/assets/6005999/d97136d6-b2f1-47a7-86bb-af750dbf2201)

**Comment by aonez** [comment] 2024-01-24 12:11
Sorry about this one @LloydThinks. This is a dupe of #1381 and it is already fixed and prepared for v1.3.7 that should be released next week.

**Comment by LloydThinks** [comment] 2024-01-24 12:21
Oh! Apologies for the duplicate report. I searched the issues and was unable to find anything.

Thank you!

**Comment by aonez** [comment] 2024-01-24 12:28
> I searched the issues and was unable to find anything

The title of the other ticket is less than ideal 😂

**Comment by aonez** [comment] 2024-01-31 12:26
Should be fixed in the current release, thanks again @LloydThinks

**Closed by aonez** 2024-01-31 12:26 UTC
Labels: bug, core, fixed
