### ISSUE TITLE
Files/folders archived separately when called via service from context menu

### ISSUE THREAD

**Issue by zanglebert** [aonez/Keka#4] opened 2016-12-01 16:05 UTC
Hey

First: great program! Thanks so much for writing & sharing this. 

Now, for a minor bug report:

System: OSX 10.11.6
Keka version: 1.0.6

Goal: create a *single* 7z archive from several input folders/files, *without* opening Keka app, i.e. by creating archive with command from context menu in Finder.

To reproduce the problem, consider the following two options to the get the intended behavior described in 'Goal' above:

Option 1: Set Keka as default archiver, use OSX default context item "Compress..."

=> Result: Keka correctly compresses several files/folder into a single file, but uses zip, not 7z, despite being selected as default format in Keka Setting. 

However, maybe that's an OSX system-wide limitation, so instead, consider the next option:

Option 2: Use service/workflow from context menu to archive/compress with Keka. In Keka settings, set 7z as default format, and check option "Archive as single file" in Preferences --> Compression

=> Result: Using service on selected files/folders, Keka now correctly uses 7z as format, but archives each file/folder *individually*, not respecting the "Archive as single file" setting apparently.

Can anyone confirm this behavior?

**Comment by aonez** [comment] 2016-12-01 16:47
@zanglebert, first thank a lot for your feedback.

About the issue, the **Option 1 can't be done** since the "Compress..." option in the context menu is never used with Keka. This option will always create a zip file with the bundled OS X/macOS compression system.

About the **Option 2**, the "Archive as single files" option does just that, archive each file/folder separately. Maybe I can change the text to "Archive each file/folder separately". So the result you're getting is correct with this option. Anyway, with this option unchecked the result is the same, it is a known bug: http://trac.kekaosx.com/ticket/127

So, uncheck the "Archive as single files" option if you don't want to archive each file separately and while it is not fixed just drop the files to the Keka icon in the dock or the Keka main window.

**Comment by zanglebert** [comment] 2016-12-01 18:02
Thanks for the response. Didn't know it's a known issue.

But there's another one:

When dropping *folders* to Keka icon, with 'Archive as single files' unchecked, it work as intended.
However, then dropping several *files* to the icon, they are archived individually, despite the unchecked option.

That's not intended, right?

**Comment by aonez** [comment] 2016-12-01 18:36
Can't reproduce this one. Can you double check you have "Archive as single files" unchecked booth in the preferences and in the main window? (if Keka is opened).

**Comment by zanglebert** [comment] 2016-12-01 21:34
You're right, tested again, working as intended now. My mistake, must have had one of the two still checked.

**Comment by aonez** [comment] 2016-12-02 02:22
I'll keep this open since the workflow need to be fixed. Thanks for all your feedback @zanglebert 👍

**Comment by zanglebert** [comment] 2016-12-03 10:26
you're welcome, least I can do :)

**Comment by aonez** [comment] 2017-02-26 03:30
Fixed in r1741. Context menu services will be integrated in the app, with a check to install or uninstall. New users will have them by default, current users will have them if they had the old context menu installed, otherwise they'll need to enable them with the check in the Preferences.

**Closed** 2017-02-28 22:27 UTC
Labels: bug, context menu
