### ISSUE TITLE
[BUG] If a file inside a zip has emojis in it's filename, Keka asks for encoding but there are no encoding options that would include emojis

### ISSUE THREAD

**Issue by Piipperi** [aonez/Keka#1021] opened 2022-01-24 18:13 UTC
### Configuration
- Keka version: 1.2.52 (4877)
- macOS version: 12.1 (21C52)

### Describe the bug
If I try to extract a zip, that has a file inside it that has emojis in its filename, Keka asks for encoding for the file, however, there are no options that would include emojis. With all encoding options present, they just turn into random garbage depending on the encoding chosen.
I should add that the same behavior does happen with The Unarchiver, however, the default macOS Archive Utility is able to extract the zip with no problem with the emojis still in the filename intact.

[Keka.log](https://github.com/aonez/Keka/files/7927870/Keka.log)

### To Reproduce
1. Make a zip file containing a file named with an emoji or emojis
2. Unzip it with Keka, which should then ask for encoding for the file
3. Realize there's no encoding option that would seem to support emojis
4. Try unzipping the same zip with Archive Utility, and the emojis should be there on the resulting file.

### Expected behavior
An encoding option that supports emojis

**Comment by aonez** [comment] 2022-02-01 18:52
Probably a dupe of https://github.com/aonez/Keka/issues/577, will check for it

**Comment by aonez** [comment] 2022-02-02 10:36
Should be fixed in the next release. Check this build: [Keka-1.2.53.r4895](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-1.2.53.r4895.7z)

**Closed** 2022-04-01 08:36 UTC
Labels: bug, unar, fixed, pre-released
