### ISSUE TITLE
[REQ] Contents Preview

### ISSUE THREAD

**Issue by SlashhLuca** [aonez/Keka#584] opened 2020-07-14 14:13 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Having the possibility to preview archives contents, without extracting them.
Something like the preview feature available on Microsoft Windows for ZIP files.
When I say "preview", I mean quickly viewing the list of files contained in archive and eventually their attributes.
However archives protected by passwords will require to put it before having the output.
The best would be allowing also to copy the list of contents into the clipboard as a text stream.
Preview could be available in 3 ways:
- Pressing "space bar" button in the mac keyboard as done for other files
- Adding "Preview" feature as a specific Keka option (more difficult from a UX and dev point of view) in Keka menu or Actions available in Finder
- Right Clicking on an archive and providing "Preview" on context menu inside Finder 

I suppose that this feature will involve using some temporary folder and clean it whenever a preview is closed or eventually manage this cleanse process by proper options among app "preferences".

**Describe alternatives you've considered**
Now it is only possible to extract the archive, browse contents and then delete them.

**Additional context**
In case an archive is "small" preview could be also availiable "automatically" in the preview box or icon inside Finder (icon, column and gallery view modes) when clicking on the archive.
In "column view mode" the a "dream-feature" would be having the list of files in the column next to the archive.
"Small" could be a parameter defined in app "preferences" and based on archive's volume in KB/MB.
"automatically" means that it is triggered just clicking on the archive in the Finder. 
"automatically" could be a parameter defined in app "preferences" and managed as a switch to choose if activate automatic preview feature.

**Comment by aonez** [comment] 2020-07-14 16:51
Thanks a lot for the detailed issue @SlashhLuca! This is a dupe of #100, any further development will go there.

**Closed by aonez** 2020-07-14 16:51 UTC
Labels: duplicated, enhancement
