### ISSUE TITLE
Sparkle update is aborted if Keka is opened to expand an archive because Keka quits after expansion

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#155] opened 2018-03-21 15:13 UTC
Reproduce:
1. use an old version of Keka
2. double click an archive to open in Keka and expand
3. Sparkle recognises an update
4. Click _Install Update_
5. wait whilst Sparkle and Keka race to the finish

Actual:
Keka closes after it has finished processing the queue
If the Sparkle update is part way through, it is lost as the app quits

Expected:
An in-progress Sparkle update should prevent Keka from closing after it finishes the queue

**Comment by aonez** [comment] 2018-03-22 08:13
I've did tested that in the past... And now following your steps but unable to reproduce. Tried with beta.6 and beta.7 on OS X 10.11 and macOS 10.13.

When you say "Download & Install", you mean this window, right?
![screen shot 2018-03-22 at 09 01 40](https://user-images.githubusercontent.com/480163/37758342-25669828-2db0-11e8-9bc9-5f9e8c1711f4.png)

A quick test is open and old beta, initiate the update process (the window above counts for the test), then close the Keka window. That update window should be keeping Keka from closing.

**Comment by aonez** [comment] 2018-03-22 08:17
If you still can reproduce, please make a video, maybe it will give me more clues.

**Comment by gingerbeardman** [comment] 2018-03-22 13:42
Yes that window.

Can I reset the "last sparkle check" so that it checks on first run?

**Comment by gingerbeardman** [comment] 2018-03-22 14:20
I have tried to reproduce but I cannot. I guess it was a race condition of some sort?

**Comment by aonez** [comment] 2018-03-22 15:06
If you have `SUEnableAutomaticChecks` set on `TRUE`, just delete `SULastCheckTime` and it will check the next time you open Keka.

Note that with the beta I've changed the behaviour of the check, and it only checks once you've done an operation, to be less intrusive.

**Comment by aonez** [comment] 2018-03-22 15:21
What I've found is that if automatic update is activated (transparently update), this can in fact be interrupted since it uses no windows.

**Comment by aonez** [comment] 2018-04-04 07:58
Fixed for beta.9, releasing it in a few!

**Closed** 2018-04-04 07:58 UTC
Labels: bug
