### ISSUE TITLE
[BUG] Slow enumeration phase & crash while compressing a lot of files

### ISSUE THREAD

**Issue by own2pwn** [aonez/Keka#652] opened 2020-10-14 16:26 UTC
### Configuration
- Keka version: `1.2.0-rc.1 (4128)`
- macOS version: `10.15.6 (19G2021)`

Hey aonez, thanks for Keka!
This happens when `archive separately` checked

If you try to compress a lot of files(150+)  which are not very small(say 10+ MB) keka has degradation while enumerating them(?) -- that happens before compression actually accurs(I believe we don't need to wait till all files processed, but can start to compress them one by one) and then it may randomly crash. I didn't save crash log but it has smth regarding of invalidation NSWindow drag zone not on main thread.

**Comment by aonez** [comment] 2020-10-15 09:42
Thanks a lot for the feedback @own2pwn!

You're very right, already enhanced the performance of this process, you can try it here: [Keka-v1.2.0-rc.1.r4143.7z](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-v1.2.0-rc.1.r4143.7z)

> may randomly crash. I didn't save crash log but it has smth regarding of invalidation NSWindow drag zone not on main thread

Maybe you can find the crash log in the Console.app - Crash Reports? It would be very helpful 😊🤞🏼

**Comment by own2pwn** [comment] 2020-10-15 10:28
By some reason I haven't found the most recent crash logs, but there are some from a previous beta version. Hope these would be helpful too!
(https://1drv.ms/u/s!AnwBE8_y0Z_WvEtLKtmkfEZO4TdV?e=0ozhw0)

**Comment by own2pwn** [comment] 2020-10-15 10:31
3 of them seems to be identical, leading to `'NSWindow drag regions should only be invalidated on the Main Thread!'` 

and the another one has a strange issue with metal?.. `Assertion failed: (surf != nullptr), function clear_region, file /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/QuartzCore/QuartzCore-841.4/LayerKit/ogl/ogl-metal.mm, line 3507.`

**Comment by own2pwn** [comment] 2020-10-15 10:34
Btw, these gradient progress bars are cool!

**Comment by aonez** [comment] 2020-10-15 10:38
Thanks a lot @own2pwn! I'll be checking crash file #2 (NSWindow drag) although it was produced with an early dev 3900 version (not even beta).

> Btw, these gradient progress bars are cool!

Thanks! I really love them 😄

**Comment by aonez** [comment] 2020-10-19 09:42
I can't really debug those logs anymore since I don't have the proper build files to do so... If your reproduce them agsain with a current build let me know.

Check the build on https://github.com/aonez/Keka/issues/652#issuecomment-709048210 and let me know if that fixes the main issue (performance) :)

**Comment by own2pwn** [comment] 2020-10-25 10:10
Hey aonez! Sorry I didn't check the optimized version. I'll try to find time in a few days

**Comment by aonez** [comment] 2020-11-10 11:56
Closing this one as 1.2.0 is released with the performance enhancements :)

**Closed by aonez** 2020-11-10 11:56 UTC
Labels: bug, fixed, performance
