### ISSUE TITLE
Can't quit Keka

### ISSUE THREAD

**Issue by criswaller** [aonez/Keka#709] opened 2020-11-29 23:26 UTC
### 👉 To fix this issue update to `v1.2.8` or newer

Due to a bug in the terminate code, if you have "Automatically download and install updates in the future" selected in a version between versions `1.2.0` and `1.2.7` Keka will need to be force-quit after it automatically updates in the background. More detailed info in https://github.com/aonez/Keka/issues/709#issuecomment-766878978.

# Original report

I cannot quit Keka from the Dock, Force Quit or Activity Monitor. I had to use killall from Terminal.

**Comment by aonez** [comment] 2020-11-30 08:18
Hi @criswaller,

Does this happens always? Only after extracting/compressing specific files? Can you check if there's any log from Keka in the Console.app?

Thanks!

**Comment by cryptochrome** [comment] 2020-12-02 23:15
I can confirm this issue exists. I have the same problem. I haven't found a pattern yet on when it happens or under what circumstances. It just happens every time I use Keka. The process doesn't react to sigterm or quitting through Finder.

**Comment by aonez** [comment] 2020-12-03 14:42
Wops...  @cryptochrome not sure what's happening there. Can you enable the "Enable debug information" and "Save debug information" and once you reproduce the issue share with me the logs of Keka?

You can disable the Finder Extension meanwhile, not sure why you have that many. macOS is the one that spawns/kills it, not Keka directly.

@franckm-rait are you having the same problem? Not able to close Keka or too many Finder Extensions?

**Comment by franckm-rait** [comment] 2020-12-03 15:10
@aonez Yes, exactly the same problem. When I use Keka on Big Sure (X86), I can't shutdown the computer without Force Quit Keka.

Seems not to be linked to the extraction of certain type of file. Not checked on extension.

**Comment by nighto** [comment] 2020-12-14 16:41
Happens with me as well. When you press Quit button, it only minimizes the application; the icon remains on the Dock with the running dot symbol.

```
arlindo.pereira@nb-apereira ~ % ps xau | grep eka
arlindo.pereira  24299   0.0  0.1  4450912  10408   ??  Ss   10:15PM   0:00.68 /Applications/Keka.app/Contents/PlugIns/KekaFinderIntegration.appex/Contents/MacOS/KekaFinderIntegration
arlindo.pereira  23983   0.0  0.1  4450912  10224   ??  Ss   10:00PM   0:00.66 /Applications/Keka.app/Contents/PlugIns/KekaFinderIntegration.appex/Contents/MacOS/KekaFinderIntegration
arlindo.pereira  23832   0.0  0.1  4450912  10172   ??  Ss    9:55PM   0:00.67 /Applications/Keka.app/Contents/PlugIns/KekaFinderIntegration.appex/Contents/MacOS/KekaFinderIntegration
arlindo.pereira   1363   0.0  0.0  4415900      8   ??  Ss   Thu05PM   0:00.09 /Applications/Keka.app/Contents/XPCServices/org.sparkle-project.InstallerConnection.xpc/Contents/MacOS/org.sparkle-project.InstallerConnection
arlindo.pereira    847   0.0  0.0  4428392    108   ??  Ss   Thu05PM   0:00.78 /Applications/Keka.app/Contents/XPCServices/org.sparkle-project.InstallerLauncher.xpc/Contents/MacOS/org.sparkle-project.InstallerLauncher
arlindo.pereira    674   0.0  0.0  4431968    756   ??  Ss   Thu05PM   0:01.43 /Applications/Keka.app/Contents/XPCServices/org.sparkle-project.Downloader.xpc/Contents/MacOS/org.sparkle-project.Downloader
arlindo.pereira    665   0.0  0.0  4454960   5372   ??  Ss   Thu05PM   0:01.93 /Applications/Keka.app/Contents/PlugIns/KekaFinderIntegration.appex/Contents/MacOS/KekaFinderIntegration
arlindo.pereira    658   0.0  0.0  4369664      8   ??  Ss   Thu05PM   0:00.06 /Applications/Keka.app/Contents/XPCServices/org.sparkle-project.InstallerStatus.xpc/Contents/MacOS/org.sparkle-project.InstallerStatus
arlindo.pereira    562   0.0  0.2  5008364  35560   ??  S    Thu05PM   0:07.66 /Applications/Keka.app/Contents/MacOS/Keka -psn_0_98328
arlindo.pereira  42189   0.0  0.0  4268216    556 s000  R+    4:38PM   0:00.00 grep eka
```

The log just says:

```
2020-12-14 16:33:05.419 DEV: Update in progress, closing automatically when done...
2020-12-14 16:34:35.234 DEV: Update in progress, closing automatically when done...
```

Disabling the extension on Keka's Preferences window won't change the situation.

If it helps I can also record a short video.

Thanks in advance.

**Comment by Oleg-Chashko** [comment] 2020-12-14 17:52
Hi @aonez 
This is one way to cause this bug.

<img width="1118" alt="Screenshot 2020-12-14 at 18 51 59" src="https://user-images.githubusercontent.com/62497891/102116583-7746fc00-3e3d-11eb-8b61-8b73aa89ee62.png">

[Screen Recording 2020-12-14 at 18.46.26.zip](https://github.com/aonez/Keka/files/5690628/Screen.Recording.2020-12-14.at.18.46.26.zip)

**Comment by Oleg-Chashko** [comment] 2020-12-14 18:50
@aonez
Long way to trigger a bug, using a script.

<img width="1326" alt="Screenshot 2020-12-14 at 19 48 31" src="https://user-images.githubusercontent.com/62497891/102122188-6c906500-3e45-11eb-9454-abdec9cc10c9.png">

Script:
[Keka - Automator.zip](https://github.com/aonez/Keka/files/5690910/Keka.-.Automator.zip)

[Screen Recording 2020-12-14 at 19.41.46.zip](https://github.com/aonez/Keka/files/5690915/Screen.Recording.2020-12-14.at.19.41.46.zip)

**Comment by gingerbeardman** [comment] 2020-12-14 20:17
These "Keka Finder Integration" processes are managed by macOS and it keeping them around is by design. See: https://github.com/knurling/ServiceStation/issues/17

If there's an issue with Keka itself quitting, then that must be considered separately.

**Comment by Oleg-Chashko** [comment] 2020-12-14 20:53
Hi @gingerbeardman 
The integration of the Keka into the context menu also disappears.
Although "Keka Finder Integration" seems to be included, there is actually no integration in the context menu.

**Comment by aonez** [comment] 2020-12-16 08:18
@nighto does this happens constantly for you? Does it not update eventually? At least now I have something to test 😉

**Comment by Oleg-Chashko** [comment] 2020-12-16 08:48
Hi @aonez 
_These "Keka Finder Integration" processes are managed by macOS and it keeping them around is by design._
Is this really normal for MacOS? o_0
<img width="1417" alt="Screenshot 2020-12-16 at 09 43 13" src="https://user-images.githubusercontent.com/62497891/102325759-d44cca00-3f83-11eb-9fff-8bd866454501.png">

**Comment by nighto** [comment] 2020-12-16 08:57
@aonez yeah, it is always present on alt-tab; if I press Cmd+Q it only minimizes, does not close. Somewhat annoying but I'm ignoring it so far :P

**Comment by aonez** [comment] 2020-12-16 09:06
@Oleg-Chashko let's follow that other issue here: https://github.com/aonez/Keka/issues/734

**Comment by aonez** [comment] 2020-12-16 09:10
@nighto what version of Keka are you using? If you disable "Automatically check for updates" in Keka's Preferences it still refuses to quit?

**Comment by nighto** [comment] 2020-12-16 09:14
@aonez it's `Version 1.2.0 (4179)`. Indeed, unchecking the Check for updates checkbox solved the issue.

**Comment by aonez** [comment] 2020-12-16 09:18
Thanks for the feedback @nighto! So clearly at least that version has an issue updating. Can you manually update to the [latest v1.2.5](https://d.keka.io), and see (in the next days) if the error reproduces with "Automatically check for updates" enabled?

@criswaller @cryptochrome @franckm-rait are you running the latest version of Keka?

**Comment by cryptochrome** [comment] 2020-12-16 11:01
I can confirm 1.2.5 fixes the issue for me. App quits just fine now. I also don't seem to have dozens of Finder Integration processes anymore.

Kudos for fixing it! 👍

**Comment by nighto** [comment] 2020-12-16 11:39
@aonez I can confirm it has been fixed as well. Thanks a lot! :)

**Comment by IvanStanul** [comment] 2020-12-16 15:46
Confirming also that new update fixed the problem for me, thanks!

**Comment by Stanzilla** [comment] 2021-01-16 01:41
I noticed the same, always when there is an update, keka won't close and I have to force quit it, sometimes multiple times. last noticed it with the update to 1.2.7 today

**Comment by aonez** [comment] 2021-01-25 15:04
Thanks for the feedback @Stanzilla and all of you.

Finally fixed this one. This only happens when you have "Automatically download and install updates in the future" selected so Keka updates in the background. Once the update is downloaded and installed Keka is unable to quit due a bug in the terminate code. This is fixed in the upcoming v1.2.8.

I recommend all affected with this issue to call "Check for updates" to update to v1.2.8 or even download the full Keka package and install it manually. Once in that new version the automatic download in the background will work flawlessly.

I'll be updating the main topic of the issue with this instructions for newcomers.

**Comment by nighto** [comment] 2021-01-25 15:18
Hi, just happened to me a few minutes ago while trying to upgrade MacOS to Big Sur.

<img width="548" alt="Screenshot 2021-01-25 at 11 54 34" src="https://user-images.githubusercontent.com/397851/105725131-7dda9000-5f20-11eb-871e-ff45b90773ab.png">

had to manually open a terminal, grep for `eka` and manually kill the processes to be able to continue the installation.

**Comment by aonez** [comment] 2021-01-25 15:28
Yep @nighto... I'm releasing `v1.2.8` hopefully tomorrow. Sorry about that!

**Comment by aonez** [comment] 2021-01-27 12:54
1.2.8 and subsequently a hotfix 1.2.9 has been released. Closing this one. Thanks to all!

**Closed by aonez** 2021-01-27 12:54 UTC
Labels: blessed, bug, fixed, workaround

**Comment by nighto** [comment] 2021-01-27 13:05
Thank you @aonez =)
