### ISSUE TITLE
.ZIP Icon broken in Mac OS Catalina

### ISSUE THREAD

**Issue by melo1529** [aonez/Keka#660] opened 2020-11-10 20:39 UTC
### Configuration
- Keka version: 1.2 
- macOS version: 10.5.6

### Describe the bug
For months now, the Mac OS Catalina has the .zip file icon showing as a white page with the keka icon in the center. I purchased Keka not only for its un-archive powers, but the clean design and icons. All other file types .rar, .7z, etc all show proper icons except for the .zip file. I've attached screenshots of what it looks like on my end, and what it should look like. I cannot find a solution to this problem anywhere, and was hoping that version 1.2 would solve this.

### Screenshots
<img width="124" alt="Screen Shot 2020-11-10 at 3 36 54 PM" src="https://user-images.githubusercontent.com/74269414/98730712-b085db00-236a-11eb-87e0-7cbb89ba9df7.png">
<img width="85" alt="Screen Shot 2020-11-10 at 3 38 05 PM" src="https://user-images.githubusercontent.com/74269414/98730771-bf6c8d80-236a-11eb-94a6-a14d339500b5.png">

**Comment by aonez** [comment] 2020-11-10 20:54
This is a dupe of #453. This is a issue of Catalina and is fixed (mostly) in Big Sur.

**Closed** 2020-11-10 20:55 UTC
Labels: bug, duplicated
