### ISSUE TITLE
How do I add a file to an existing keka zip?

### ISSUE THREAD

**Issue by Gewurztraminer** [aonez/Keka#1072] opened 2022-03-11 18:09 UTC
How do I add a file to an existing keka zip?

**Comment by aonez** [comment] 2022-03-11 18:21
This is currently no possible with Keka.

**Comment by scratch-er** [comment] 2022-05-14 07:07
Unpack it, copy the file to add into the directory, than re-pack.
And I think it's time for Keka to add more feathures rather than focus on only simplicity.

**Comment by mbirth** [comment] 2023-01-10 16:36
Duplicate of #231

**Closed** 2023-01-10 16:39 UTC
Labels: duplicated, enhancement, core
