### ISSUE TITLE
How to preview the contents of the compressed file before decompression?

### ISSUE THREAD

**Issue by eddi-z97** [aonez/Keka#909] opened 2021-08-01 08:41 UTC

**Comment by welby12** [comment] 2021-08-04 22:49
+1 This would definitely be a useful feature

**Comment by mbirth** [comment] 2023-01-10 14:57
Duplicate of #100

**Comment by aonez** [comment] 2023-01-10 15:38
Thanks @mbirth.

This is also already implemented in the iOS version:

https://ios.keka.io

**Closed** 2023-01-10 15:38 UTC
Labels: enhancement
