### ISSUE TITLE
window stays open after extraction

### ISSUE THREAD

**Issue by getmonyinfo** [aonez/Keka#471] opened 2019-10-28 03:44 UTC
current version： 1.1.21 (3378)
The window stays open after extraction， i have checked “Close keka when no windows are open"

**Comment by aonez** [comment] 2019-10-28 08:00
This is a dupe of #307. Can you uncheck and check "Close Keka when no windows are open". If this does not solve the issue, just reset the Keka preferences. Close Keka and then execute this command in the Terminal.app:

```sh
k='com.aone.keka'; rm ~/Library/Preferences/$k; rm -r ~/Library/Containers/$k;
```

**Comment by getmonyinfo** [comment] 2019-10-28 12:28
I follow you step:

1.  `ncheck and check "Close Keka when no windows are open"` no lucky
2. `k='com.aone.keka'; rm ~/Library/Preferences/$k; rm -r ~/Library/Containers/$k; ` no lucky
3. `reinstall keka` no lucky

any tips to debug why not working?

**Comment by aonez** [comment] 2019-10-28 12:43
Can you share a video capture of the issue? (for example capture the screen using QuickTime)

Also please try the latest beta version and let me know if has the issue too: https://beta.keka.io

**Comment by getmonyinfo** [comment] 2019-10-29 03:02
[a demo video](https://www.youtube.com/watch?v=e72YO-0RDVM)

**Comment by aonez** [comment] 2019-10-29 10:49
Thanks a lot for the video @getmonyinfo. This one remembers me a lot to #38 ([demo video](https://www.youtube.com/watch?v=Kmnb3lPO-08)) that was caused by a SIMBL plugin (afloat). But again this was already fixed.

Can you reproduce the issue with [this build](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-471.7z) and let me know what messages Keka prints in the Console.app? Mostly need the order of the printed messages starting with `--`, like:
```
default	11:36:19.473211 +0100	Keka	-- applicationWillBecomeActive
```

Also please try the latest beta, since it behaves different from the current stable releases, and I'm mostly sure it will work there: [Keka v1.2.0-dev.3575](https://github.com/aonez/Keka/releases/tag/v1.2.0-dev.3575)

---

For resetting Keka preferences you only need to delete the container folder:

```
rm -r ~/Library/Containers/com.aone.keka
```

The first time you opened Keka it loaded with the legacy toolbar and when you clicked on the Preferences menu option it did not opened and the second time opened without loading any content, so that tells me maybe the `find` command did not worked as expected.

**Comment by aonez** [comment] 2019-10-29 10:59
> any tips to debug why not working?

You can also get more Keka logs if you want: https://github.com/aonez/Keka/wiki/Console-verbose

**Comment by aonez** [comment] 2019-11-07 20:16
@getmonyinfo where you able to test the build? Does this issue still happens for you?

**Closed** 2019-11-14 21:00 UTC
Labels: core, gui, more info needed

**Comment by aonez** [comment] 2022-02-13 15:00
If you’ve already deleted the preferences of Keka then most probably there’s a third party app that’s activating Keka twice. This happened in the past with an app I can’t remember right now.

Can you replicate the issue in a new user account in your Mac?

**Comment by Stooovie** [comment] 2022-02-13 15:11
Yes I can replicate with a new user account. It happened the first time I've tried. I tried several more times and it was a roughly 50/50 chance. Super weird.
