### ISSUE TITLE
[BUG] Keka not extracting applications correctly on M1 Chip

### ISSUE THREAD

**Issue by TechVader** [aonez/Keka#827] opened 2021-04-14 22:22 UTC
### Configuration
- Keka version: Version 1.2.12 (4522)
- Chip: Apple M1
- macOS version: 11.2.3 (20D91)

### Describe the bug
I've only tried this with two different applications, but when trying to extract the **[Brooklyn](https://github.com/pedrommcarrasco/Brooklyn/releases/download/2.1.0/Brooklyn.saver.zip)** screensaver, it seemed to extract correctly, but then led to an issue were it could not be installed. However, I was able to extract that same file correctly using Apple's Archive Utility.

In addition, I had to setup my printer at home, and downloaded the **[HP Easy Start](https://ftp.hp.com/pub/softlib/software12/HP_Quick_Start/osx/Applications/HP_Easy_Start.app.zip)** app. Again, when I went to extract it with Keka, the App Icon showed a 🚫 symbol over it and I was not able to run the installer. However, again, I was able to extract the application correctly using Apple's Archive Utility.

### To Reproduce
1. Double-click on .zip file
2. Error when trying to run/open file

### Expected behavior
The first time the screensaver file was supposed to install itself into the system when I double-clicked on the .screensaver file. The second time, I was supposed to be able to open the HP Easy Start app, but it didn't load.

### Screenshots
When extracting with Keka:
<img width="116" alt="image" src="https://user-images.githubusercontent.com/1923370/114787656-00f7cf00-9d35-11eb-8f3d-12f8cb42cf8c.png">
When extracting with Archive Utility:
<img width="119" alt="image" src="https://user-images.githubusercontent.com/1923370/114787733-1a008000-9d35-11eb-947b-a2b430049206.png">

**Comment by MaxPower85** [comment] 2021-04-15 04:43
Since most Mac users don't have an M1 Mac yet to test, it might help resolve that issue more quickly if you could include more info about it...

If you could try to see is something different when you "right click" on the app and go to "Show Package Contents"... you could maybe check are some files missing and compare the file sizes.

Also, try it with formats other than .zip, to see there a similar issues with those too or not.

**Comment by aonez** [comment] 2021-04-15 06:52
Thanks for the feedback @TechVader! I'll try today with an M1. Already tried with Intel and works as expected. I'll let you know my results.

**Comment by TechVader** [comment] 2021-04-19 06:01
> Thanks for the feedback @TechVader! I'll try today with an M1. Already tried with Intel and works as expected. I'll let you know my results.

Were you able to recreate the same issue?

**Comment by aonez** [comment] 2021-04-19 06:50
@TechVader I was able to briefly test in a M1 but did not reproduced the issue. Could you [create a debug session in Keka](https://github.com/aonez/Keka/wiki/Report-an-issue#debug-session), reproduce the issue and share the log file?

**Comment by TechVader** [comment] 2021-04-19 16:41
I've included it here:
https://gist.github.com/TechVader/e157cb0a3e4cc4a5b41949f852d1f2fe

**Comment by aonez** [comment] 2021-04-21 07:20
Strange, the logs feels pretty much what should be...

**Comment by aonez** [comment] 2021-04-21 07:24
I'm gonna get an M1 to properly test it, give me a few days.

**Comment by aonez** [comment] 2021-04-21 07:33
If you could try those:

- Try extracting it using `p7zip`:

   Set `UnzipWithUNAR` to `FALSE` using the Terminal. Restart Keka before trying the extraction.
   ```
   defaults write com.aone.keka UnzipWithUNAR -bool FALSE
   ```
   Revert this after the test, Keka works better with `UnzipWithUNAR` be set to `TRUE`.

- Disable "Inherit quarantine from downloaded files" in the Keka Preferences and repeat the extraction.

Let me know if any of those have any difference in the extraction.

**Comment by TechVader** [comment] 2021-04-21 17:34
* Using `7z x <filename>`:
  * I was able to extract both of those same .zip files successfully.

* Setting `UnzipWithUNAR` to `FALSE`:
  * Brooklyn.saver.zip was successfully extracted and I was able to install it just fine.
  * HP_Easy_Start.app.zip still gave me the following icon:
<img width="116" alt="114787656-00f7cf00-9d35-11eb-8f3d-12f8cb42cf8c" src="https://user-images.githubusercontent.com/1923370/115596163-a4446900-a28c-11eb-8866-78470a6cf592.png">

* Disabling "Inherit quarantine from downloaded files:
  * Both files were still not usable once extracted.

**Comment by TechVader** [comment] 2021-04-22 06:45
### Eureka!!! ###
It's not you, it's me. Before I even created this issue thread, I deleted the Keka.app and re-downloaded it from the MAS, but still ran into the issue. Then I deleted Keka.app again and installed it directly from Keka's website, and still had the same issue. This is why I posted in the first place.

So since you could not reproduce the error, I started thinking that it has to be me. We tried all those things above and it didn't work. So then I started thinking that maybe my application isn't corrupt, but maybe something in my preferences.

This time I installed **[AppCleaner](https://freemacsoft.net/appcleaner/)** and uninstalled Keka (along with the preferences and any associated files). Then I restarted my machine, downloaded a fresh copy from Keka's website, then installed it. I opened it up, set up my preferences, then quit the application.

I went to finder, extracted the Brooklyn.saver.zip, and it seemed to extract ok. Then I double-clicked on the file, and it worked perfectly. So I then tried the HP Easy Start app, extracted it, and voila! It was good.

So in the end, it seems it was a corrupt preference file or something.

Thank you for all your help in trying to get this fixed.

I ❤️ Keka and I didn't want to have to abandon it due to something like this. I'm glad I got this resolved.

**Comment by aonez** [comment] 2021-04-22 09:48
> It's not you, it's me

Never thought this phrase will make me happy 😂 Anyway a M1 MacBook Air is already coming...

If you use Time Machine maybe you can recover the Keka preferences that seemed to be creating the issue (from 3-4 days ago) so I can try replicate it and fix it:

```
~/Library/Containers/com.aone.keka/Data/Library/Preferences/com.aone.keka.plist
```

Thanks again for all the feedback and the love, @TechVader.

**Comment by TechVader** [comment] 2021-04-22 16:49
I actually had a feeling you'd want to take a look, so i saved it. I opened it up in XCode, but I don't really see anything out of the ordinary either, but you might.
[com.aone.keka.plist.zip](https://github.com/aonez/Keka/files/6359972/com.aone.keka.plist.zip)

 So here it is:

**Comment by aonez** [comment] 2021-04-30 09:46
Wow, this is the plist from the MAS installation... I'm don't even know how this plist was there. Anyway tried with that and Keka rebuild the preferences, no bad extraction either.

You took that plist from the path I've referred?

```
~/Library/Containers/com.aone.keka/Data/Library/Preferences/com.aone.keka.plist
```

**Comment by TechVader** [comment] 2021-05-01 21:45
That was the only plist that was in the Trash can that my application uninstaller placed in there.

**Comment by aonez** [comment] 2021-05-04 07:13
Anyhow, thanks a lot for all the feedback @TechVader. I now have an M1 for future tests. Closing this one now 🙏🏻

**Closed by aonez** 2021-05-04 07:13 UTC
Labels: M1, works for me
