### ISSUE TITLE
Cannot dismiss "failed extract/bad password" dialog using keyboard

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#161] opened 2018-03-31 14:58 UTC
![screen shot 2018-03-31 at 15 55 51](https://user-images.githubusercontent.com/49612/38164412-36aacc1e-34fc-11e8-94cd-215d91c958b9.png)

things I tried:
- tab to get to X
- enter to select default option
- space to select alternative default
- Cmd+W to close window

**Comment by aonez** [comment] 2018-04-01 08:16
Can you replicate it? Most surely the process crashed internally. Maybe take a look at the Console.app logs (filter by Keka).

**Comment by gingerbeardman** [comment] 2018-04-01 09:25
I'll reproduce and upload a file soon

**Comment by gingerbeardman** [comment] 2018-04-01 18:22
OK, you can reproduce with any archive that is password protected.

1. Double click the archive 
2. Enter incorrect password
3. Try to dismiss dialog with "failed" message

[test.zip](https://github.com/aonez/Keka/files/1866590/test.zip)
pass: Keka

**Comment by aonez** [comment] 2018-04-01 19:04
Can't reproduce it. There's any log con the console once you click the close button?

**Comment by gingerbeardman** [comment] 2018-04-01 22:03
So what happens when you enter the wrong pass on an archive? Can you close it using keyboard? 

I can click the close button, of course, but the issue is that I can't close it using only the keyboard.

**Comment by aonez** [comment] 2018-04-02 06:59
Sorry missed the "keyboard" in the title 😅 Since multitasking was implemented in Keka, the keyboard shortcuts for pause/stop where removed. You can still close the app with "cmd+Q".

But will be interesting adopting (at least) those:

> - tab to get to X
> - Cmd+W to close window

**Comment by aonez** [comment] 2020-06-03 08:28
This is fixed in 1.2.0! Both the `x` button  and <kbd>cmd</kbd>+<kbd>w</kbd> will work.

**Closed** 2020-11-03 11:18 UTC
Labels: enhancement, fixed, gui
