### ISSUE TITLE
Progress bar disappears if you leave Keka open and compress something the 2nd time

### ISSUE THREAD

**Issue by MaxPower85** [aonez/Keka#789] opened 2021-02-16 11:08 UTC
Tested it on Sierra... not sure if it happens on other macOS versions...

If you open Keka and compress something, the progress bar appears as it should the 1st time... but if you leave Keka open and try to compress another file, the progress bar is missing...

If you try to resize the notification that is supposed to have a progress bar, then the progress bar appears again and everything works fine (it doesn't disappear anymore if you compress more files) until you close Keka...

After you close Keka, then when you try to compress something it will appear again, but when you try to compress some other file, then it's missing again until you resize the notification.

**Comment by aonez** [comment] 2021-02-17 09:35
Glad to hear again from your @MaxPower85.

I did find this a while ago. This started as soon as constraints were implemented in the interface. I’ve limited the task window size in old macOS versions, but clearly this appeared again. I’ll check later.

**Comment by aonez** [comment] 2021-02-23 18:26
@MaxPower85 just tested latest version on 10.12 Sierra and can't reproduce the issue.

Can you check you are using latest version and maybe do a screencast?

**Comment by aonez** [comment] 2021-02-23 18:31
I reproduced it (again) on 10.10 Yosemite 😤

**Comment by aonez** [comment] 2021-02-23 18:35
> Can you check you are using latest version and maybe do a screencast?

If you can do it anyway, I can't reproduce it in 10.11 or newer with latest version.

**Comment by MaxPower85** [comment] 2021-03-01 03:31
I checked again with the latest version of Keka... I first deleted Keka and I deleted Keka's preferences, to make sure that wasn't causing an issue...

It seems to happen every time after the first time you compress something and leave Keka opened... until you close Keka or resize the notification... then the issue disappears until you close Keka and compress something again... after that it happens again.

If you are maybe doing the testing in a VM, maybe it doesn't appear when non-Retina resolutions are used.

**Comment by aonez** [comment] 2021-03-01 15:53
👍🏼 retina was it @MaxPower85. Reproduced on 10.12 now.

**Comment by aonez** [comment] 2021-03-01 16:25
Can't reproduce it on 10.13 or newer.

**Comment by aonez** [comment] 2021-03-01 18:42
@MaxPower85 should be fixed in this build: [Keka-1.2.12-r4511](https://github.com/aonez/Keka/releases/download/dev-test-builds/Keka-1.2.12-r4511.7z)

**Comment by MaxPower85** [comment] 2021-03-07 00:58
I tried it now... yeah... it's fixed in that version :)

**Comment by aonez** [comment] 2021-03-11 09:29
1.2.12 released!

**Closed by aonez** 2021-03-11 09:29 UTC
Labels: bug, fixed, gui
