### ISSUE TITLE
Unzipped applications appear to be created by Keka

### ISSUE THREAD

**Issue by NosillaCast** [aonez/Keka#215] opened 2018-06-14 17:11 UTC
I just downloaded an app called "HashPhotos Transfer.app" as a zip archive. Since Keka is my default now, it opened the zip for me. When I opened the app though, I got the macOS Gatekeeper message "HashPhotos Transfer.app is an application created by Keka Are you sure you want to open it?"

I wouldn't think that's intended behavior?

<img width="420" alt="keka created app" src="https://user-images.githubusercontent.com/12651464/41427297-54a90ca4-6fbb-11e8-833c-02909cbedcf0.png">

**Comment by aonez** [comment] 2018-06-22 21:09
I'm fixing this one first, since it has some nasty effects: https://twitter.com/the_jannis/status/1010259254043955200

**Comment by aonez** [comment] 2018-06-22 21:29
@NosillaCast it did not affected me neither but the `xScope` package he shared reproduces the issue 😕

**Comment by aonez** [comment] 2018-07-09 11:59
This is being help by Apple in the review process. Might need to find a workaround.

**Comment by aonez** [comment] 2018-09-24 08:00
As reported via mail, [Sublime Merge](https://www.sublimemerge.com/download) also has this issue, with the addition that it does render the package "unidentifiable" and it can't be opened:

![screen shot 2018-09-24 at 09 57 28](https://user-images.githubusercontent.com/480163/45941891-833a0f80-bfe0-11e8-8a26-f1ce5d7a7a1d.png)

A workaround is right click (or control click) and Open:

![screen shot 2018-09-24 at 09 57 37](https://user-images.githubusercontent.com/480163/45941919-a06ede00-bfe0-11e8-97e4-2d78cc91cd53.png)

**Comment by aonez** [comment] 2020-06-03 08:23
Maybe in the future Apple will allow the use of `com.apple.security.files.user-selected.executable` so this can be properly fixed. Until then #405 is the only workaround.

**Comment by aonez** [comment] 2020-12-18 13:57
This is fixed with the "Inherit quarantine from downloaded files" option in 1.2.0. This option is enabled by default.

Thanks again @NosillaCast!

**Closed by aonez** 2020-12-18 13:57 UTC
Labels: bug, core, sandbox
