### ISSUE TITLE
ZIPed postscript font’s with resource forks not working

### ISSUE THREAD

**Issue by JadKey** [aonez/Keka#430] opened 2019-07-16 14:15 UTC
Hi, I have a number projects ziped using Keka, some of my work uses the older postscript fonts, unfortunately zipping or unzipping my old files the font’s come out as zero k (The resource forks in the fonts get discarded.) and can no longer be used.
  
Apple’s ZIP has no problems keeping the fonts usable can this be fixed in Keka?

**Comment by gingerbeardman** [comment] 2019-07-16 14:43
Did you check your prefs? 

![Screen shot 2019-07-16 at 15 42 26](https://user-images.githubusercontent.com/49612/61304016-6295ad00-a7e0-11e9-87b1-680672cdb07c.png)

**Comment by aonez** [comment] 2019-07-17 08:00
@JadKey although Keka is able to extract those files from a ZIP since 1.1.6 version, it is still unable to properly compress them using the ZIP format. You can use TAR (tar.bz2, tar.gz and so on) instead.

This is a duplicate of https://github.com/aonez/Keka/issues/90

**Closed** 2019-07-17 08:00 UTC
Labels: duplicated
