### ISSUE TITLE
ePub extraction

### ISSUE THREAD

**Issue by jerryevo** [aonez/Keka#86] opened 2017-10-18 09:00 UTC
ePub are in fact ZIP files. When extracting them using KEKA instead of folder user gets bundle. This is not convenient.

**Comment by aonez** [comment] 2017-10-18 09:03
I'm not sure what you mean. If I extract an ePub, the result will be a folder with all it's contents. What do you mean with "user gets bundle"?

**Comment by aonez** [comment] 2017-10-18 09:09
For example if you extract [this randomly selected ePub](http://www.gutenberg.org/ebooks/55764) (ePub with or without images), what you get?

**Comment by jerryevo** [comment] 2017-10-18 09:12
Bundle, like APP bundle. To get into I need to rightclick it and use option "show bundle content". The same ePub extracted with , for example "The Unarchiver" will get standard folder.

**Comment by aonez** [comment] 2017-10-18 14:42
So you're getting a folder with extension? What extension is that? Can your share an ePud that causes this issue?

**Comment by aonez** [comment] 2017-10-18 16:42
I've made some tests and adding `epub` extension to a folder makes it a bundle. So I suppose you extracted an ePub and it retained the extension, ain't it?

**Comment by jerryevo** [comment] 2017-10-19 06:12
Example ePub you can find here: http://www.gutenberg.org/ebooks/55764.epub.images
Download it
Then extract with Keka - you will get bundle
Delete bundle and extract with The Unarchiver - you will get Folder

**Comment by aonez** [comment] 2017-10-19 08:07
Can't really reproduce this. What version of Keka are you using? Any special configuration?

![untitled mov](https://user-images.githubusercontent.com/480163/31760512-350cddf6-b4b5-11e7-9fac-09ba0575ad9e.gif)

**Comment by jerryevo** [comment] 2017-10-19 09:14
I'm using 1.1.0-beta.4 (2296), but problem exists for long time and in previous versions too.
There is inconsistent behaviour. When extracting as you show it above it works ok.
But change .epub to .epub.zip, Keka as app to open ZIP files and then double click ZIP.

**Comment by aonez** [comment] 2017-10-19 09:22
But the premise of adding `.zip` extension is incorrect since `.epub` already implies it is a zip.

Maybe the way to go with this is adding `.epub` to the recognised extraction formats, so the default action using Keka will be extract it, therefore you don't need to change the ePub extension to `.zip` or drop it in the extraction zone.

Will it make sense to you?

**Comment by jerryevo** [comment] 2017-10-19 09:26
Default handler for epub files is iBooks for many Mac users, I think. It is much easier to add .zip at the end of file name and then open it with default handler for ZIP files, which is Keka in my case.
For me it is logical.
But despite of this: there is difference in behaviour when epub is opened in Keka app (as handler) or dropped on Keka dialog to extract.

**Comment by aonez** [comment] 2021-12-08 12:29
Added them (as well as a bunch more e-book zip extensions). Also with bundle/framework detection enhancements in the current Keka version @jerryevo issue (`.epub.zip`) will not be present anymore.

So properly fixing this issue.

**Comment by aonez** [comment] 2022-01-17 16:07
Fixed in 1.2.51 😊

**Closed by aonez** 2022-01-17 16:07 UTC
Labels: question, works for me, fixed
