### ISSUE TITLE
[REQ]Can you add password manager to Keka? 

### ISSUE THREAD

**Issue by JOJOforshaun** [aonez/Keka#826] opened 2021-04-10 06:35 UTC
This is very convenient and can save a lot of time for activities that often need to unpack compressed files of the same or several passwords. I even want Keka to be able to automatically traversal the passwords saved in the password manager when it unpacks the encrypted zip file.

**Comment by gingerbeardman** [comment] 2021-04-10 13:02
I wonder if Keychain is a good place for such passwords to be stored?

**Comment by aonez** [comment] 2021-04-12 10:06
@JOJOforshaun this is a dupe of #26, will be tracked there :)

**Closed by aonez** 2021-04-12 10:06 UTC
Labels: duplicated, enhancement
