### ISSUE TITLE
Dock icon problem

### ISSUE THREAD

**Issue by 0x1301FDF** [aonez/Keka#344] opened 2018-12-13 08:30 UTC
i select some docx,xlxs files and drop them to dock icon,however there are only docx files in  the compressed file

**Comment by 0x1301FDF** [comment] 2018-12-14 02:36
i drop 6 files to dock icon(4 docx, 2  Axure RP file),try both zip and 7z, the result is same: only 4 docx files  in the compressed file.
Drop to the keka windows is ok! 6 files in it.
These file names are in Chinese, but I renamed it to English, and try again,the result is same,only 4 files.

**Comment by 0x1301FDF** [comment] 2018-12-14 02:40
none or the fastest compression method also the same result, only 4 docx files

**Comment by 0x1301FDF** [comment] 2018-12-14 02:49
i upload my 6 files to my github,you can download it to test.
https://github.com/0x1301FDF/0x1301FDF.github.io/raw/master/test.zip

**Comment by aonez** [comment] 2018-12-14 09:30
@0x1301FDF can't reproduce the issue with the test files. This surely has to do with #77, but it is strange you only get one compressed file. Can you enable the [verbose mode](https://github.com/aonez/Keka/wiki/Console-verbose) and let me know what the Console.app says?

```sh
defaults write com.aone.keka DevLog -bool TRUE
```

Note that you can use the drop in the window or the contextual menu items, both should work.

![untitled 2](https://user-images.githubusercontent.com/480163/49994952-23258a80-ff8b-11e8-90a8-edd3038cba77.png)

**Comment by 0x1301FDF** [comment] 2018-12-15 13:57
@aonez i enable the verbose mode and the Console.app says ：
默认	21:47:59.243253 +0800	launchservicesd	CHECKIN:0x0-0x3b93b9 28349 com.aone.keka
默认	21:47:59.351155 +0800	Keka	Updating user defaults from 3160...
默认	21:47:59.352703 +0800	Keka	Dev mode enabled
默认	21:47:59.355970 +0800	Keka	Running on OS X/macOS 版本 10.13.6（版号 17G4015）
默认	21:47:59.356792 +0800	Keka	Running sandboxed Keka (WEB) version 1.1.8 (3160)
默认	21:47:59.358739 +0800	Keka	Used localization: zh-Hans
错误	21:47:59.494691 +0800	Keka	        AEGetDescData of non-desc type 'reco' not a good idea
默认	21:47:59.500867 +0800	Keka	Requesting access to all bookmarks...
默认	21:47:59.501932 +0800	Keka	Bookmarks updated: 1
默认	21:48:09.332729 +0800	Keka	LSExceptions shared instance invalidated for timeout.
默认	21:48:26.753918 +0800	Keka	Adding 4 files
默认	21:48:26.755120 +0800	Keka	Waiting for more input: 0.250000
默认	21:48:27.022006 +0800	Keka	Set tarball: 0. Tarball active: 0. Extension: 7z
默认	21:48:27.023205 +0800	Keka	Detecting common path...
默认	21:48:27.027282 +0800	Keka	Binary used: keka7z
默认	21:48:27.028574 +0800	Keka	Arguments: (
    a,
    "-t7z",
    "-mx5",
    "-ms=on",
    "/Users/myname/Downloads/\U538b\U7f29\U540e\U7684\U6587\U4ef6.7z",
    "test4.docx",
    "test5.docx",
    "test1.docx",
    "test6.docx"
)
默认	21:48:27.532396 +0800	Keka	done: 1
默认	21:48:27.583063 +0800	Keka	HALC_ProxyObject.cpp:184:GetPropertyDataSize:  HALC_ProxyObject::GetPropertyDataSize ('stm#', 'inpt', 0, AI32): got an error from the server, 0x77686F3F
默认	21:48:27.583207 +0800	Keka	HALC_ProxyObject.cpp:462:GetPropertyData:  HALC_ProxyObject::GetPropertyData ('stm#', 'inpt', 0, DAI32): got an error from the server, 0x77686F3F
默认	21:48:27.586606 +0800	Keka	HALC_ProxyObject.cpp:184:GetPropertyDataSize:  HALC_ProxyObject::GetPropertyDataSize ('stm#', 'inpt', 0, AI32): got an error from the server, 0x77686F3F
默认	21:48:27.586728 +0800	Keka	HALC_ProxyObject.cpp:462:GetPropertyData:  HALC_ProxyObject::GetPropertyData ('stm#', 'inpt', 0, DAI32): got an error from the server, 0x77686F3F


the Arguments show only 4 files.
 use the drop in the window or the contextual menu items,both works well.

**Comment by 0x1301FDF** [comment] 2018-12-15 14:17
that seems macOS's bug!! i drop 6 files to another application ,also 4 files get in window.

**Comment by aonez** [comment] 2018-12-17 14:18
@0x1301FDF I'm closing this one in favor of #77, since it is essentially the same issue. I hope the alternatives (drop in the window and context menu) are 👍🏼 for you. Thanks for all the feedback!

**Closed by aonez** 2018-12-17 14:18 UTC
