### ISSUE TITLE
App quits after extraction whilst Sparkle update alert is on screen

### ISSUE THREAD

**Issue by gingerbeardman** [aonez/Keka#408] opened 2019-05-04 20:35 UTC
![Screen shot 2019-05-04 at 21 33 20](https://user-images.githubusercontent.com/49612/57184517-7190e280-6eb4-11e9-8848-47aeb78e3125.png)

Once the app is quit, the only way to get this auto update notice is to:
1. manually refresh
2. wait

both are less than ideal.

would it be preferable to wait if the Sparkle dialog is showing?

**Comment by aonez** [comment] 2019-05-04 21:39
I can't reproduce this one, if the update window is shown, Keka stays opened for me. Did the window appeared automagically for you while extracting? I'll do more tests.

**Comment by gingerbeardman** [comment] 2019-05-04 21:58
> Did the window appeared automagically for you while extracting? 

Yes

**Comment by aonez** [comment] 2019-06-12 10:12
I'm reopening this one, should be already fixed in 1.2.0

**Comment by aonez** [comment] 2019-10-10 16:45
Was closed by mistake 😅

**Comment by gingerbeardman** [comment] 2020-10-18 12:57
I got this again yesterday

**Comment by aonez** [comment] 2021-01-12 17:27
I'm investigating #709 and reproduced your issue @gingerbeardman. Hopefully I can fix both issues at one!

**Comment by aonez** [comment] 2021-01-25 14:54
@gingerbeardman this should be fixed in 1.2.8.

The problem was that when "Install Update" button is pressed that window closes. If there're no other Keka windows open and is set to "Close Keka when no windows are open" Keka quits before the update process window appears.

**Comment by gingerbeardman** [comment] 2021-01-25 16:24
Hoorah!

**Closed** 2021-11-06 23:24 UTC
Labels: enhancement, fixed
