### ISSUE TITLE
[REQ] - List Archive contents

### ISSUE THREAD

**Issue by jonn-set** [aonez/Keka#1526] opened 2024-10-05 09:36 UTC
### Is your feature request related to a problem? Please describe
Would like to request a new feature where you can view the contents of an Archive before extracting it like WinZip, WinRar, etc

### Describe the solution you'd like
A mini Finder like window to view the contents before extracting. Its an enhancement.

### Describe alternatives you've considered
PeaZip, but the app is too slow and clunky, new version crashes often.

### Additional context
No.

**Comment by aonez** [comment] 2024-10-15 11:15
This is a duplicate of #100.

**Closed by aonez** 2024-10-15 11:15 UTC
Labels: duplicated, enhancement
