### ISSUE TITLE
Chinese file name is decoded in a wrong way after unarchiving

### ISSUE THREAD

**Issue by guori12321** [aonez/Keka#113] opened 2017-11-23 06:04 UTC
If I compress the files whose names are in English into a ZIP package, and then unarchive it, then the file name will be decoded in a wrong way and thus meaningless to me. How to fix that? I guess this is a decoding error, right?

**Comment by aonez** [comment] 2017-11-23 10:27
You compress this Zip files using Keka?

Maybe this is a duplicate of https://github.com/aonez/Keka/issues/12

**Comment by guori12321** [comment] 2017-11-23 14:17
Nope. If the zip is compressed on Windows and then unarchived on Mac via keka, then I'll have the trouble.

Yes it is the same problem described in #12 . I believe this is a encoding/decoding problem because Windows and Mac OS X may use the different default encoding charsets.

Sorry I didn't find any dialog box to choose the decoding charset when unarchive. Is it fixed or not yet?

**Comment by aonez** [comment] 2017-11-24 20:29
Sorry @guori12321 it’s not fixed yet. I close this ticket since it’s a duplicate of #12.

**Closed by aonez** 2017-11-24 20:29 UTC
