### ISSUE TITLE
Extract wrong filename

### ISSUE THREAD

**Issue by nuomi1** [aonez/Keka#65] opened 2017-08-25 11:15 UTC
Keka 1.1.0 beta 3
macOS 10.12.6, zh-Hans

Original: `万能驱动精简视频教程FOR10.mp4`
Actual: `ÍòÄÜÇý¶¯¾«¼òÊÓÆµ½Ì³ÌFOR10.mp4`

[万能驱动精简视频教程FOR10.zip](https://github.com/aonez/Keka/files/1251681/FOR10.zip)

**Comment by aonez** [comment] 2017-09-05 08:33
With the bundled macOS archiver: `ÕÚƒ‹«˝∂Øæ´ºÚ ”∆µΩÃ≥ÃFOR10.mp4`
With UnZip 5.52: `-=-_ò»%A5%BD+=-%CB%E3%C1%A2%A6%A6%A6FOR10.mp4`

Do you know what compressor was used in other to create this file?

**Comment by nuomi1** [comment] 2017-09-05 11:32
I don't know the compressor was used for this file.

The filename is correct with the bundled macOS archiver in `10.12.6 & zh-Hans`.

**Comment by aonez** [comment] 2017-09-13 13:28
I mark this as a duplicate of #12

**Closed by aonez** 2017-09-13 13:28 UTC
Labels: bug, core
