### ISSUE TITLE
[BUG] Finder extensions corrupt sidebar icons for external disks

### ISSUE THREAD

**Issue by jacksprattt1234** [aonez/Keka#806] opened 2021-02-25 05:00 UTC
### Configuration
- Keka version: 1.2.11 (4493)
- macOS version: 11.2.1

### Describe the bug
If the keka Finder Extensions are enabled in the macOS Extensions preference pane, icons for external disks are no longer correct in the Finder's sidebar. The external disk icon is replaced by a generic document icon.

### To Reproduce
1. Enable the checkbox for Keka's 'Finder Extensions' in the macOS Extensions preference pane.
2. Open a new finder window.
3. Sidebar icons for external disks are replaced with a generic document icon.

### Expected behavior
Finder sidebar icons should not be affected.

### Screenshots
Extensions disabled:
![Screen Shot Disabled](https://user-images.githubusercontent.com/13994163/109105412-ba95d480-76e2-11eb-9f03-6e36aef22931.png)

Extensions enabled:
![Screen Shot Enabled](https://user-images.githubusercontent.com/13994163/109105738-5de6e980-76e3-11eb-9c59-1ffa90d90f90.png)

**Comment by aonez** [comment] 2021-02-25 21:12
Thanks for the feedback! This is a duplicate of https://github.com/aonez/Keka/issues/667

Check it out and reopen if that does not fix your issue.

**Closed** 2021-02-25 21:13 UTC
Labels: Apple SDK, bug, duplicated
