### ISSUE TITLE
Error code 3 using "unrar"

### ISSUE THREAD

**Issue by macsavant** [aonez/Keka#341] opened 2018-12-03 05:50 UTC
Receive this error from Keka when trying to unrar files from one of my sources.

Error code 3 using "unrar"
CRC error occurred, maybe the file is corrupt

Files unrar without error with UnrarX. Files from all other sources unrar without incident. Started happening with the latest update of Keka to v1.1.7.

**Comment by aonez** [comment] 2018-12-03 07:51
@macsavant are those files password protected? Maybe this is the same issue as #335?

If you can, check if this works with [Keka 1.1.5](https://github.com/aonez/Keka/releases/tag/v1.1.5).

**Comment by aonez** [comment] 2018-12-03 09:32
@macsavant check if it works with the build linked here: https://github.com/aonez/Keka/issues/335#issuecomment-443644260

**Comment by macsavant** [comment] 2018-12-04 09:04
Yes, they are password protected.

I tried both the 1.1.5 version as well as the more recent build of 1.1.7 you linked to. They both worked perfectly.

I'll continue to use the 1.1.7 build and wait for 1.1.8. Thank you very much for your help.

**Comment by aonez** [comment] 2018-12-04 09:15
@macsavant just pushed the 1.1.8 update. Thanks for the feedback! 😊

This was a duplicate of #335

**Closed by aonez** 2018-12-04 09:15 UTC
Labels: duplicated, unrar

**Comment by gmbh1** [comment] 2019-07-03 12:01
Hi @macsavant if you've not solved the issue, I think I have a solution. the .rar file you are trying to unzip isn't corrupt or locked it's just part of another file.

**Comment by aonez** [comment] 2019-07-04 10:01
@gmbh1 the issue here was solved, it was about the password.
